//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/xml/simpleparser/IanaEncodings.java
//

#ifndef _ComItextpdfTextXmlSimpleparserIanaEncodings_H_
#define _ComItextpdfTextXmlSimpleparserIanaEncodings_H_

@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface ComItextpdfTextXmlSimpleparserIanaEncodings : NSObject {
}

+ (NSString *)getJavaEncodingWithNSString:(NSString *)iana;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextXmlSimpleparserIanaEncodings_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextXmlSimpleparserIanaEncodings)

FOUNDATION_EXPORT id<JavaUtilMap> ComItextpdfTextXmlSimpleparserIanaEncodings_MAP_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextXmlSimpleparserIanaEncodings, MAP_, id<JavaUtilMap>)

#endif // _ComItextpdfTextXmlSimpleparserIanaEncodings_H_
