//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/impl/xpath/XMPPathParser.java
//

#ifndef _ComItextpdfXmpImplXpathXMPPathParser_H_
#define _ComItextpdfXmpImplXpathXMPPathParser_H_

#include "J2ObjC_header.h"

@class ComItextpdfXmpImplXpathXMPPath;

@interface ComItextpdfXmpImplXpathXMPPathParser : NSObject

#pragma mark Public

+ (ComItextpdfXmpImplXpathXMPPath *)expandXPathWithNSString:(NSString *)schemaNS
                                               withNSString:(NSString *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfXmpImplXpathXMPPathParser)

FOUNDATION_EXPORT ComItextpdfXmpImplXpathXMPPath *ComItextpdfXmpImplXpathXMPPathParser_expandXPathWithNSString_withNSString_(NSString *schemaNS, NSString *path);

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfXmpImplXpathXMPPathParser)

@interface ComItextpdfXmpImplXpathPathPosition : NSObject {
 @public
  NSString *path_;
  jint nameStart_;
  jint nameEnd_;
  jint stepBegin_;
  jint stepEnd_;
}

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfXmpImplXpathPathPosition)

J2OBJC_FIELD_SETTER(ComItextpdfXmpImplXpathPathPosition, path_, NSString *)

FOUNDATION_EXPORT void ComItextpdfXmpImplXpathPathPosition_init(ComItextpdfXmpImplXpathPathPosition *self);

FOUNDATION_EXPORT ComItextpdfXmpImplXpathPathPosition *new_ComItextpdfXmpImplXpathPathPosition_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfXmpImplXpathPathPosition)

#endif // _ComItextpdfXmpImplXpathXMPPathParser_H_
