//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/security/ExternalSignatureContainer.java
//

#ifndef _ComItextpdfTextPdfSecurityExternalSignatureContainer_H_
#define _ComItextpdfTextPdfSecurityExternalSignatureContainer_H_

@class ComItextpdfTextPdfPdfDictionary;
@class IOSByteArray;
@class JavaIoInputStream;

#import "JreEmulation.h"

@protocol ComItextpdfTextPdfSecurityExternalSignatureContainer < NSObject, JavaObject >

- (IOSByteArray *)signWithJavaIoInputStream:(JavaIoInputStream *)data;

- (void)modifySigningDictionaryWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)signDic;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfSecurityExternalSignatureContainer_init() {}

#endif // _ComItextpdfTextPdfSecurityExternalSignatureContainer_H_
