//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/security/ExternalBlankSignatureContainer.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/security/ExternalBlankSignatureContainer.java"

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "com/itextpdf/text/pdf/PdfDictionary.h"
#include "com/itextpdf/text/pdf/PdfName.h"
#include "com/itextpdf/text/pdf/security/ExternalBlankSignatureContainer.h"
#include "java/io/InputStream.h"
#include "java/security/GeneralSecurityException.h"


#line 57
@implementation ComItextpdfTextPdfSecurityExternalBlankSignatureContainer


#line 60
- (instancetype)initWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)sigDic {
  if (self = [super init]) {
    
#line 61
    self->sigDic_ = sigDic;
  }
  return self;
}


#line 64
- (instancetype)initWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)filter
                    withComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)subFilter {
  if (self = [super init]) {
    
#line 65
    sigDic_ = [[ComItextpdfTextPdfPdfDictionary alloc] init];
    
#line 66
    [sigDic_ putWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_FILTER_() withComItextpdfTextPdfPdfObject:filter];
    
#line 67
    [sigDic_ putWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_SUBFILTER_() withComItextpdfTextPdfPdfObject:subFilter];
  }
  return self;
}


#line 70
- (IOSByteArray *)signWithJavaIoInputStream:(JavaIoInputStream *)data {
  
#line 71
  return [IOSByteArray arrayWithLength:0];
}


#line 74
- (void)modifySigningDictionaryWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)signDic {
  
#line 75
  [((ComItextpdfTextPdfPdfDictionary *) nil_chk(signDic)) putAllWithComItextpdfTextPdfPdfDictionary:sigDic_];
}

- (void)copyAllFieldsTo:(ComItextpdfTextPdfSecurityExternalBlankSignatureContainer *)other {
  [super copyAllFieldsTo:other];
  other->sigDic_ = sigDic_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComItextpdfTextPdfPdfDictionary:", "ExternalBlankSignatureContainer", NULL, 0x1, NULL },
    { "initWithComItextpdfTextPdfPdfName:withComItextpdfTextPdfPdfName:", "ExternalBlankSignatureContainer", NULL, 0x1, NULL },
    { "signWithJavaIoInputStream:", "sign", "[B", 0x1, "Ljava.security.GeneralSecurityException;" },
    { "modifySigningDictionaryWithComItextpdfTextPdfPdfDictionary:", "modifySigningDictionary", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "sigDic_", NULL, 0x2, "Lcom.itextpdf.text.pdf.PdfDictionary;", NULL,  },
  };
  static const J2ObjcClassInfo _ComItextpdfTextPdfSecurityExternalBlankSignatureContainer = { "ExternalBlankSignatureContainer", "com.itextpdf.text.pdf.security", NULL, 0x1, 4, methods, 1, fields, 0, NULL};
  return &_ComItextpdfTextPdfSecurityExternalBlankSignatureContainer;
}

@end
