//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/html/WebColors.java
//

#ifndef _ComItextpdfTextHtmlWebColors_H_
#define _ComItextpdfTextHtmlWebColors_H_

@class ComItextpdfTextBaseColor;

#import "JreEmulation.h"
#include "java/util/HashMap.h"

#define ComItextpdfTextHtmlWebColors_serialVersionUID 3542523100813372896LL

@interface ComItextpdfTextHtmlWebColors : JavaUtilHashMap {
}

+ (jboolean)missingHashColorFormatWithNSString:(NSString *)colStr;

+ (ComItextpdfTextBaseColor *)getRGBColorWithNSString:(NSString *)name;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextHtmlWebColors_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextHtmlWebColors)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextHtmlWebColors, serialVersionUID, jlong)

FOUNDATION_EXPORT ComItextpdfTextHtmlWebColors *ComItextpdfTextHtmlWebColors_NAMES_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextHtmlWebColors, NAMES_, ComItextpdfTextHtmlWebColors *)

#endif // _ComItextpdfTextHtmlWebColors_H_
