//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/interfaces/IAccessibleElement.java
//

#ifndef _ComItextpdfTextPdfInterfacesIAccessibleElement_H_
#define _ComItextpdfTextPdfInterfacesIAccessibleElement_H_

@class ComItextpdfTextAccessibleElementId;
@class ComItextpdfTextPdfPdfName;
@class ComItextpdfTextPdfPdfObject;
@class JavaUtilHashMap;

#import "JreEmulation.h"

@protocol ComItextpdfTextPdfInterfacesIAccessibleElement < NSObject, JavaObject >

- (ComItextpdfTextPdfPdfObject *)getAccessibleAttributeWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)key;

- (void)setAccessibleAttributeWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)key
                            withComItextpdfTextPdfPdfObject:(ComItextpdfTextPdfPdfObject *)value;

- (JavaUtilHashMap *)getAccessibleAttributes;

- (ComItextpdfTextPdfPdfName *)getRole;

- (void)setRoleWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)role;

- (ComItextpdfTextAccessibleElementId *)getId;

- (void)setIdWithComItextpdfTextAccessibleElementId:(ComItextpdfTextAccessibleElementId *)id_;

- (jboolean)isInline;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfInterfacesIAccessibleElement_init() {}

#endif // _ComItextpdfTextPdfInterfacesIAccessibleElement_H_
