//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/codec/LZWCompressor.java
//

#ifndef _ComItextpdfTextPdfCodecLZWCompressor_H_
#define _ComItextpdfTextPdfCodecLZWCompressor_H_

#include "J2ObjC_header.h"

@class ComItextpdfTextPdfCodecBitFile;
@class ComItextpdfTextPdfCodecLZWStringTable;
@class IOSByteArray;
@class JavaIoOutputStream;

@interface ComItextpdfTextPdfCodecLZWCompressor : NSObject {
 @public
  jint codeSize__;
  jint clearCode__;
  jint endOfInfo__;
  jint numBits__;
  jint limit__;
  jshort prefix__;
  ComItextpdfTextPdfCodecBitFile *bf__;
  ComItextpdfTextPdfCodecLZWStringTable *lzss__;
  jboolean tiffFudge__;
}

#pragma mark Public

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                                   withInt:(jint)codeSize
                               withBoolean:(jboolean)TIFF;

- (void)compressWithByteArray:(IOSByteArray *)buf
                      withInt:(jint)offset
                      withInt:(jint)length;

- (void)flush;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfCodecLZWCompressor)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfCodecLZWCompressor, bf__, ComItextpdfTextPdfCodecBitFile *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfCodecLZWCompressor, lzss__, ComItextpdfTextPdfCodecLZWStringTable *)

FOUNDATION_EXPORT void ComItextpdfTextPdfCodecLZWCompressor_initWithJavaIoOutputStream_withInt_withBoolean_(ComItextpdfTextPdfCodecLZWCompressor *self, JavaIoOutputStream *outArg, jint codeSize, jboolean TIFF);

FOUNDATION_EXPORT ComItextpdfTextPdfCodecLZWCompressor *new_ComItextpdfTextPdfCodecLZWCompressor_initWithJavaIoOutputStream_withInt_withBoolean_(JavaIoOutputStream *outArg, jint codeSize, jboolean TIFF) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfCodecLZWCompressor)

#endif // _ComItextpdfTextPdfCodecLZWCompressor_H_
