//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/events/PdfPageEventForwarder.java
//

#ifndef _ComItextpdfTextPdfEventsPdfPageEventForwarder_H_
#define _ComItextpdfTextPdfEventsPdfPageEventForwarder_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/pdf/PdfPageEvent.h"

@class ComItextpdfTextDocument;
@class ComItextpdfTextParagraph;
@class ComItextpdfTextPdfPdfWriter;
@class ComItextpdfTextRectangle;
@class JavaUtilArrayList;

@interface ComItextpdfTextPdfEventsPdfPageEventForwarder : NSObject < ComItextpdfTextPdfPdfPageEvent > {
 @public
  JavaUtilArrayList *events_;
}

#pragma mark Public

- (instancetype)init;

- (void)addPageEventWithComItextpdfTextPdfPdfPageEvent:(id<ComItextpdfTextPdfPdfPageEvent>)event;

- (void)onChapterWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                     withComItextpdfTextDocument:(ComItextpdfTextDocument *)document
                                       withFloat:(jfloat)paragraphPosition
                    withComItextpdfTextParagraph:(ComItextpdfTextParagraph *)title;

- (void)onChapterEndWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                        withComItextpdfTextDocument:(ComItextpdfTextDocument *)document
                                          withFloat:(jfloat)position;

- (void)onCloseDocumentWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                           withComItextpdfTextDocument:(ComItextpdfTextDocument *)document;

- (void)onEndPageWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                     withComItextpdfTextDocument:(ComItextpdfTextDocument *)document;

- (void)onGenericTagWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                        withComItextpdfTextDocument:(ComItextpdfTextDocument *)document
                       withComItextpdfTextRectangle:(ComItextpdfTextRectangle *)rect
                                       withNSString:(NSString *)text;

- (void)onOpenDocumentWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                          withComItextpdfTextDocument:(ComItextpdfTextDocument *)document;

- (void)onParagraphWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                       withComItextpdfTextDocument:(ComItextpdfTextDocument *)document
                                         withFloat:(jfloat)paragraphPosition;

- (void)onParagraphEndWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                          withComItextpdfTextDocument:(ComItextpdfTextDocument *)document
                                            withFloat:(jfloat)paragraphPosition;

- (void)onSectionWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                     withComItextpdfTextDocument:(ComItextpdfTextDocument *)document
                                       withFloat:(jfloat)paragraphPosition
                                         withInt:(jint)depth
                    withComItextpdfTextParagraph:(ComItextpdfTextParagraph *)title;

- (void)onSectionEndWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                        withComItextpdfTextDocument:(ComItextpdfTextDocument *)document
                                          withFloat:(jfloat)position;

- (void)onStartPageWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                       withComItextpdfTextDocument:(ComItextpdfTextDocument *)document;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfEventsPdfPageEventForwarder)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfEventsPdfPageEventForwarder, events_, JavaUtilArrayList *)

FOUNDATION_EXPORT void ComItextpdfTextPdfEventsPdfPageEventForwarder_init(ComItextpdfTextPdfEventsPdfPageEventForwarder *self);

FOUNDATION_EXPORT ComItextpdfTextPdfEventsPdfPageEventForwarder *new_ComItextpdfTextPdfEventsPdfPageEventForwarder_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfEventsPdfPageEventForwarder)

#endif // _ComItextpdfTextPdfEventsPdfPageEventForwarder_H_
