//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/crypto/ARCFOUREncryption.java
//

#ifndef _ComItextpdfTextPdfCryptoARCFOUREncryption_H_
#define _ComItextpdfTextPdfCryptoARCFOUREncryption_H_

@class IOSByteArray;

#import "JreEmulation.h"

@interface ComItextpdfTextPdfCryptoARCFOUREncryption : NSObject {
 @public
  IOSByteArray *state_;
  jint x_;
  jint y_;
}

- (instancetype)init;

- (void)prepareARCFOURKeyWithByteArray:(IOSByteArray *)key;

- (void)prepareARCFOURKeyWithByteArray:(IOSByteArray *)key
                               withInt:(jint)off
                               withInt:(jint)len;

- (void)encryptARCFOURWithByteArray:(IOSByteArray *)dataIn
                            withInt:(jint)off
                            withInt:(jint)len
                      withByteArray:(IOSByteArray *)dataOut
                            withInt:(jint)offOut;

- (void)encryptARCFOURWithByteArray:(IOSByteArray *)data
                            withInt:(jint)off
                            withInt:(jint)len;

- (void)encryptARCFOURWithByteArray:(IOSByteArray *)dataIn
                      withByteArray:(IOSByteArray *)dataOut;

- (void)encryptARCFOURWithByteArray:(IOSByteArray *)data;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfCryptoARCFOUREncryption *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfCryptoARCFOUREncryption_init() {}

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfCryptoARCFOUREncryption, state_, IOSByteArray *)

#endif // _ComItextpdfTextPdfCryptoARCFOUREncryption_H_
