//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/error_messages/MessageLocalization.java
//

#ifndef _ComItextpdfTextError_messagesMessageLocalization_H_
#define _ComItextpdfTextError_messagesMessageLocalization_H_

@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaIoReader;
@class JavaUtilHashMap;

#import "JreEmulation.h"

@interface ComItextpdfTextError_messagesMessageLocalization : NSObject {
}

- (instancetype)init;

+ (NSString *)getMessageWithNSString:(NSString *)key;

+ (NSString *)getMessageWithNSString:(NSString *)key
                         withBoolean:(jboolean)useDefaultLanguageIfMessageNotFound;

+ (NSString *)getComposedMessageWithNSString:(NSString *)key
                                     withInt:(jint)p1;

+ (NSString *)getComposedMessageWithNSString:(NSString *)key
                           withNSObjectArray:(IOSObjectArray *)param;

+ (jboolean)setLanguageWithNSString:(NSString *)language
                       withNSString:(NSString *)country;

+ (void)setMessagesWithJavaIoReader:(JavaIoReader *)r;

+ (JavaUtilHashMap *)getLanguageMessagesWithNSString:(NSString *)language
                                        withNSString:(NSString *)country;

+ (JavaUtilHashMap *)readLanguageStreamWithJavaIoInputStream:(JavaIoInputStream *)is;

+ (JavaUtilHashMap *)readLanguageStreamWithJavaIoReader:(JavaIoReader *)r;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextError_messagesMessageLocalization_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextError_messagesMessageLocalization)

FOUNDATION_EXPORT JavaUtilHashMap *ComItextpdfTextError_messagesMessageLocalization_defaultLanguage_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextError_messagesMessageLocalization, defaultLanguage_, JavaUtilHashMap *)
J2OBJC_STATIC_FIELD_SETTER(ComItextpdfTextError_messagesMessageLocalization, defaultLanguage_, JavaUtilHashMap *)

FOUNDATION_EXPORT JavaUtilHashMap *ComItextpdfTextError_messagesMessageLocalization_currentLanguage_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextError_messagesMessageLocalization, currentLanguage_, JavaUtilHashMap *)
J2OBJC_STATIC_FIELD_SETTER(ComItextpdfTextError_messagesMessageLocalization, currentLanguage_, JavaUtilHashMap *)

FOUNDATION_EXPORT NSString *ComItextpdfTextError_messagesMessageLocalization_BASE_PATH_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextError_messagesMessageLocalization, BASE_PATH_, NSString *)

#endif // _ComItextpdfTextError_messagesMessageLocalization_H_
