//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/languages/BanglaGlyphRepositioner.java
//

#ifndef _ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner_H_
#define _ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/pdf/languages/IndicGlyphRepositioner.h"

@protocol JavaUtilList;
@protocol JavaUtilMap;

@interface ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner : ComItextpdfTextPdfLanguagesIndicGlyphRepositioner

#pragma mark Public

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)cmap31
                    withJavaUtilMap:(id<JavaUtilMap>)glyphSubstitutionMap;

- (id<JavaUtilList>)getCharactersToBeShiftedLeftByOnePosition;

- (void)repositionGlyphsWithJavaUtilList:(id<JavaUtilList>)glyphList;

@end

J2OBJC_STATIC_INIT(ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner)

FOUNDATION_EXPORT void ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner_initWithJavaUtilMap_withJavaUtilMap_(ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner *self, id<JavaUtilMap> cmap31, id<JavaUtilMap> glyphSubstitutionMap);

FOUNDATION_EXPORT ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner *new_ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner_initWithJavaUtilMap_withJavaUtilMap_(id<JavaUtilMap> cmap31, id<JavaUtilMap> glyphSubstitutionMap) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner)

#endif // _ComItextpdfTextPdfLanguagesBanglaGlyphRepositioner_H_
