//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/languages/IndicCompositeCharacterComparator.java
//

#ifndef _ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator_H_
#define _ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator_H_

#include "J2ObjC_header.h"
#include "java/util/Comparator.h"

@interface ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator : NSObject < JavaUtilComparator >

#pragma mark Public

- (instancetype)init;

- (jint)compareWithId:(NSString *)o1
               withId:(NSString *)o2;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator)

FOUNDATION_EXPORT void ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator_init(ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator *self);

FOUNDATION_EXPORT ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator *new_ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator)

#endif // _ComItextpdfTextPdfLanguagesIndicCompositeCharacterComparator_H_
