//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/awt/geom/gl/Crossing.java
//

#ifndef _ComItextpdfAwtGeomGlCrossing_H_
#define _ComItextpdfAwtGeomGlCrossing_H_

@class IOSDoubleArray;
@protocol ComItextpdfAwtGeomPathIterator;
@protocol ComItextpdfAwtGeomShape;

#import "JreEmulation.h"

#define ComItextpdfAwtGeomGlCrossing_CROSSING 255
#define ComItextpdfAwtGeomGlCrossing_DELTA 1.0E-5
#define ComItextpdfAwtGeomGlCrossing_ROOT_DELTA 1.0E-10
#define ComItextpdfAwtGeomGlCrossing_UNKNOWN 254

@interface ComItextpdfAwtGeomGlCrossing : NSObject {
}

+ (jint)solveQuadWithDoubleArray:(IOSDoubleArray *)eqn
                 withDoubleArray:(IOSDoubleArray *)res;

+ (jint)solveCubicWithDoubleArray:(IOSDoubleArray *)eqn
                  withDoubleArray:(IOSDoubleArray *)res;

+ (jint)fixRootsWithDoubleArray:(IOSDoubleArray *)res
                        withInt:(jint)rc;

+ (jint)crossLineWithDouble:(jdouble)x1
                 withDouble:(jdouble)y1
                 withDouble:(jdouble)x2
                 withDouble:(jdouble)y2
                 withDouble:(jdouble)x
                 withDouble:(jdouble)y;

+ (jint)crossQuadWithDouble:(jdouble)x1
                 withDouble:(jdouble)y1
                 withDouble:(jdouble)cx
                 withDouble:(jdouble)cy
                 withDouble:(jdouble)x2
                 withDouble:(jdouble)y2
                 withDouble:(jdouble)x
                 withDouble:(jdouble)y;

+ (jint)crossCubicWithDouble:(jdouble)x1
                  withDouble:(jdouble)y1
                  withDouble:(jdouble)cx1
                  withDouble:(jdouble)cy1
                  withDouble:(jdouble)cx2
                  withDouble:(jdouble)cy2
                  withDouble:(jdouble)x2
                  withDouble:(jdouble)y2
                  withDouble:(jdouble)x
                  withDouble:(jdouble)y;

+ (jint)crossPathWithComItextpdfAwtGeomPathIterator:(id<ComItextpdfAwtGeomPathIterator>)p
                                         withDouble:(jdouble)x
                                         withDouble:(jdouble)y;

+ (jint)crossShapeWithComItextpdfAwtGeomShape:(id<ComItextpdfAwtGeomShape>)s
                                   withDouble:(jdouble)x
                                   withDouble:(jdouble)y;

+ (jboolean)isZeroWithDouble:(jdouble)val;

+ (void)sortBoundWithDoubleArray:(IOSDoubleArray *)bound
                         withInt:(jint)bc;

+ (jint)crossBoundWithDoubleArray:(IOSDoubleArray *)bound
                          withInt:(jint)bc
                       withDouble:(jdouble)py1
                       withDouble:(jdouble)py2;

+ (jint)intersectLineWithDouble:(jdouble)x1
                     withDouble:(jdouble)y1
                     withDouble:(jdouble)x2
                     withDouble:(jdouble)y2
                     withDouble:(jdouble)rx1
                     withDouble:(jdouble)ry1
                     withDouble:(jdouble)rx2
                     withDouble:(jdouble)ry2;

+ (jint)intersectQuadWithDouble:(jdouble)x1
                     withDouble:(jdouble)y1
                     withDouble:(jdouble)cx
                     withDouble:(jdouble)cy
                     withDouble:(jdouble)x2
                     withDouble:(jdouble)y2
                     withDouble:(jdouble)rx1
                     withDouble:(jdouble)ry1
                     withDouble:(jdouble)rx2
                     withDouble:(jdouble)ry2;

+ (jint)intersectCubicWithDouble:(jdouble)x1
                      withDouble:(jdouble)y1
                      withDouble:(jdouble)cx1
                      withDouble:(jdouble)cy1
                      withDouble:(jdouble)cx2
                      withDouble:(jdouble)cy2
                      withDouble:(jdouble)x2
                      withDouble:(jdouble)y2
                      withDouble:(jdouble)rx1
                      withDouble:(jdouble)ry1
                      withDouble:(jdouble)rx2
                      withDouble:(jdouble)ry2;

+ (jint)intersectPathWithComItextpdfAwtGeomPathIterator:(id<ComItextpdfAwtGeomPathIterator>)p
                                             withDouble:(jdouble)x
                                             withDouble:(jdouble)y
                                             withDouble:(jdouble)w
                                             withDouble:(jdouble)h;

+ (jint)intersectShapeWithComItextpdfAwtGeomShape:(id<ComItextpdfAwtGeomShape>)s
                                       withDouble:(jdouble)x
                                       withDouble:(jdouble)y
                                       withDouble:(jdouble)w
                                       withDouble:(jdouble)h;

+ (jboolean)isInsideNonZeroWithInt:(jint)cross;

+ (jboolean)isInsideEvenOddWithInt:(jint)cross;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComItextpdfAwtGeomGlCrossing_init() {}

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomGlCrossing, DELTA, jdouble)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomGlCrossing, ROOT_DELTA, jdouble)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomGlCrossing, CROSSING, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomGlCrossing, UNKNOWN, jint)

@interface ComItextpdfAwtGeomGlCrossing_QuadCurve : NSObject {
 @public
  jdouble ax_, ay_, bx_, by_;
  jdouble Ax_, Ay_, Bx_, By_;
}

- (instancetype)initWithDouble:(jdouble)x1
                    withDouble:(jdouble)y1
                    withDouble:(jdouble)cx
                    withDouble:(jdouble)cy
                    withDouble:(jdouble)x2
                    withDouble:(jdouble)y2;

- (jint)crossWithDoubleArray:(IOSDoubleArray *)res
                     withInt:(jint)rc
                  withDouble:(jdouble)py1
                  withDouble:(jdouble)py2;

- (jint)solvePointWithDoubleArray:(IOSDoubleArray *)res
                       withDouble:(jdouble)px;

- (jint)solveExtremWithDoubleArray:(IOSDoubleArray *)res;

- (jint)addBoundWithDoubleArray:(IOSDoubleArray *)bound
                        withInt:(jint)bc
                withDoubleArray:(IOSDoubleArray *)res
                        withInt:(jint)rc
                     withDouble:(jdouble)minX
                     withDouble:(jdouble)maxX
                    withBoolean:(jboolean)changeId
                        withInt:(jint)id_;

- (void)copyAllFieldsTo:(ComItextpdfAwtGeomGlCrossing_QuadCurve *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfAwtGeomGlCrossing_QuadCurve_init() {}

@interface ComItextpdfAwtGeomGlCrossing_CubicCurve : NSObject {
 @public
  jdouble ax_, ay_, bx_, by_, cx_, cy_;
  jdouble Ax_, Ay_, Bx_, By_, Cx_, Cy_;
  jdouble Ax3_, Bx2_;
}

- (instancetype)initWithDouble:(jdouble)x1
                    withDouble:(jdouble)y1
                    withDouble:(jdouble)cx1
                    withDouble:(jdouble)cy1
                    withDouble:(jdouble)cx2
                    withDouble:(jdouble)cy2
                    withDouble:(jdouble)x2
                    withDouble:(jdouble)y2;

- (jint)crossWithDoubleArray:(IOSDoubleArray *)res
                     withInt:(jint)rc
                  withDouble:(jdouble)py1
                  withDouble:(jdouble)py2;

- (jint)solvePointWithDoubleArray:(IOSDoubleArray *)res
                       withDouble:(jdouble)px;

- (jint)solveExtremXWithDoubleArray:(IOSDoubleArray *)res;

- (jint)solveExtremYWithDoubleArray:(IOSDoubleArray *)res;

- (jint)addBoundWithDoubleArray:(IOSDoubleArray *)bound
                        withInt:(jint)bc
                withDoubleArray:(IOSDoubleArray *)res
                        withInt:(jint)rc
                     withDouble:(jdouble)minX
                     withDouble:(jdouble)maxX
                    withBoolean:(jboolean)changeId
                        withInt:(jint)id_;

- (void)copyAllFieldsTo:(ComItextpdfAwtGeomGlCrossing_CubicCurve *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfAwtGeomGlCrossing_CubicCurve_init() {}

#endif // _ComItextpdfAwtGeomGlCrossing_H_
