//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/hyphenation/ByteVector.java
//

#ifndef _ComItextpdfTextPdfHyphenationByteVector_H_
#define _ComItextpdfTextPdfHyphenationByteVector_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class IOSByteArray;

@interface ComItextpdfTextPdfHyphenationByteVector : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithByteArray:(IOSByteArray *)a;

- (instancetype)initWithByteArray:(IOSByteArray *)a
                          withInt:(jint)capacity;

- (instancetype)initWithInt:(jint)capacity;

- (jint)alloc__WithInt:(jint)size OBJC_METHOD_FAMILY_NONE;

- (jint)capacity;

- (jbyte)getWithInt:(jint)index;

- (IOSByteArray *)getArray;

- (jint)length;

- (void)putWithInt:(jint)index
          withByte:(jbyte)val;

- (void)trimToSize;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfHyphenationByteVector)

FOUNDATION_EXPORT void ComItextpdfTextPdfHyphenationByteVector_init(ComItextpdfTextPdfHyphenationByteVector *self);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationByteVector *new_ComItextpdfTextPdfHyphenationByteVector_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextPdfHyphenationByteVector_initWithInt_(ComItextpdfTextPdfHyphenationByteVector *self, jint capacity);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationByteVector *new_ComItextpdfTextPdfHyphenationByteVector_initWithInt_(jint capacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextPdfHyphenationByteVector_initWithByteArray_(ComItextpdfTextPdfHyphenationByteVector *self, IOSByteArray *a);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationByteVector *new_ComItextpdfTextPdfHyphenationByteVector_initWithByteArray_(IOSByteArray *a) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextPdfHyphenationByteVector_initWithByteArray_withInt_(ComItextpdfTextPdfHyphenationByteVector *self, IOSByteArray *a, jint capacity);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationByteVector *new_ComItextpdfTextPdfHyphenationByteVector_initWithByteArray_withInt_(IOSByteArray *a, jint capacity) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfHyphenationByteVector)

#endif // _ComItextpdfTextPdfHyphenationByteVector_H_
