//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/hyphenation/Hyphenator.java
//

#ifndef _ComItextpdfTextPdfHyphenationHyphenator_H_
#define _ComItextpdfTextPdfHyphenationHyphenator_H_

#include "J2ObjC_header.h"

@class ComItextpdfTextPdfHyphenationHyphenation;
@class ComItextpdfTextPdfHyphenationHyphenationTree;
@class IOSCharArray;

@interface ComItextpdfTextPdfHyphenationHyphenator : NSObject

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)lang
                    withNSString:(NSString *)country
                         withInt:(jint)leftMin
                         withInt:(jint)rightMin;

+ (ComItextpdfTextPdfHyphenationHyphenationTree *)getFileHyphenationTreeWithNSString:(NSString *)key;

+ (ComItextpdfTextPdfHyphenationHyphenationTree *)getHyphenationTreeWithNSString:(NSString *)lang
                                                                    withNSString:(NSString *)country;

+ (NSString *)getHyphenDir;

+ (ComItextpdfTextPdfHyphenationHyphenationTree *)getResourceHyphenationTreeWithNSString:(NSString *)key;

- (ComItextpdfTextPdfHyphenationHyphenation *)hyphenateWithCharArray:(IOSCharArray *)word
                                                             withInt:(jint)offset
                                                             withInt:(jint)len;

- (ComItextpdfTextPdfHyphenationHyphenation *)hyphenateWithNSString:(NSString *)word;

+ (ComItextpdfTextPdfHyphenationHyphenation *)hyphenateWithNSString:(NSString *)lang
                                                       withNSString:(NSString *)country
                                                      withCharArray:(IOSCharArray *)word
                                                            withInt:(jint)offset
                                                            withInt:(jint)len
                                                            withInt:(jint)leftMin
                                                            withInt:(jint)rightMin;

+ (ComItextpdfTextPdfHyphenationHyphenation *)hyphenateWithNSString:(NSString *)lang
                                                       withNSString:(NSString *)country
                                                       withNSString:(NSString *)word
                                                            withInt:(jint)leftMin
                                                            withInt:(jint)rightMin;

+ (void)setHyphenDirWithNSString:(NSString *)_hyphenDir;

- (void)setLanguageWithNSString:(NSString *)lang
                   withNSString:(NSString *)country;

- (void)setMinPushCharCountWithInt:(jint)min;

- (void)setMinRemainCharCountWithInt:(jint)min;

@end

J2OBJC_STATIC_INIT(ComItextpdfTextPdfHyphenationHyphenator)

FOUNDATION_EXPORT void ComItextpdfTextPdfHyphenationHyphenator_initWithNSString_withNSString_withInt_withInt_(ComItextpdfTextPdfHyphenationHyphenator *self, NSString *lang, NSString *country, jint leftMin, jint rightMin);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationHyphenator *new_ComItextpdfTextPdfHyphenationHyphenator_initWithNSString_withNSString_withInt_withInt_(NSString *lang, NSString *country, jint leftMin, jint rightMin) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationHyphenationTree *ComItextpdfTextPdfHyphenationHyphenator_getHyphenationTreeWithNSString_withNSString_(NSString *lang, NSString *country);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationHyphenationTree *ComItextpdfTextPdfHyphenationHyphenator_getResourceHyphenationTreeWithNSString_(NSString *key);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationHyphenationTree *ComItextpdfTextPdfHyphenationHyphenator_getFileHyphenationTreeWithNSString_(NSString *key);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationHyphenation *ComItextpdfTextPdfHyphenationHyphenator_hyphenateWithNSString_withNSString_withNSString_withInt_withInt_(NSString *lang, NSString *country, NSString *word, jint leftMin, jint rightMin);

FOUNDATION_EXPORT ComItextpdfTextPdfHyphenationHyphenation *ComItextpdfTextPdfHyphenationHyphenator_hyphenateWithNSString_withNSString_withCharArray_withInt_withInt_withInt_withInt_(NSString *lang, NSString *country, IOSCharArray *word, jint offset, jint len, jint leftMin, jint rightMin);

FOUNDATION_EXPORT NSString *ComItextpdfTextPdfHyphenationHyphenator_getHyphenDir();

FOUNDATION_EXPORT void ComItextpdfTextPdfHyphenationHyphenator_setHyphenDirWithNSString_(NSString *_hyphenDir);

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfHyphenationHyphenator)

#endif // _ComItextpdfTextPdfHyphenationHyphenator_H_
