//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/Anchor.java
//

#ifndef _ComItextpdfTextAnchor_H_
#define _ComItextpdfTextAnchor_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/Phrase.h"

@class ComItextpdfTextChunk;
@class ComItextpdfTextFont;
@class JavaNetURL;
@protocol ComItextpdfTextElementListener;
@protocol JavaUtilList;

@interface ComItextpdfTextAnchor : ComItextpdfTextPhrase {
 @public
  NSString *name_;
  NSString *reference_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithComItextpdfTextChunk:(ComItextpdfTextChunk *)chunk;

- (instancetype)initWithFloat:(jfloat)leading;

- (instancetype)initWithFloat:(jfloat)leading
     withComItextpdfTextChunk:(ComItextpdfTextChunk *)chunk;

- (instancetype)initWithFloat:(jfloat)leading
                 withNSString:(NSString *)string;

- (instancetype)initWithFloat:(jfloat)leading
                 withNSString:(NSString *)string
      withComItextpdfTextFont:(ComItextpdfTextFont *)font;

- (instancetype)initWithComItextpdfTextPhrase:(ComItextpdfTextPhrase *)phrase;

- (instancetype)initWithNSString:(NSString *)string;

- (instancetype)initWithNSString:(NSString *)string
         withComItextpdfTextFont:(ComItextpdfTextFont *)font;

- (id<JavaUtilList>)getChunks;

- (NSString *)getName;

- (NSString *)getReference;

- (JavaNetURL *)getUrl;

- (jboolean)processWithComItextpdfTextElementListener:(id<ComItextpdfTextElementListener>)listener;

- (void)setNameWithNSString:(NSString *)name;

- (void)setReferenceWithNSString:(NSString *)reference;

- (jint)type;

#pragma mark Protected

- (jboolean)applyAnchorWithComItextpdfTextChunk:(ComItextpdfTextChunk *)chunk
                                    withBoolean:(jboolean)notGotoOK
                                    withBoolean:(jboolean)localDestination;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextAnchor)

J2OBJC_FIELD_SETTER(ComItextpdfTextAnchor, name_, NSString *)
J2OBJC_FIELD_SETTER(ComItextpdfTextAnchor, reference_, NSString *)

FOUNDATION_EXPORT void ComItextpdfTextAnchor_init(ComItextpdfTextAnchor *self);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithFloat_(ComItextpdfTextAnchor *self, jfloat leading);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithFloat_(jfloat leading) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithComItextpdfTextChunk_(ComItextpdfTextAnchor *self, ComItextpdfTextChunk *chunk);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithComItextpdfTextChunk_(ComItextpdfTextChunk *chunk) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithNSString_(ComItextpdfTextAnchor *self, NSString *string);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithNSString_(NSString *string) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithNSString_withComItextpdfTextFont_(ComItextpdfTextAnchor *self, NSString *string, ComItextpdfTextFont *font);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithNSString_withComItextpdfTextFont_(NSString *string, ComItextpdfTextFont *font) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithFloat_withComItextpdfTextChunk_(ComItextpdfTextAnchor *self, jfloat leading, ComItextpdfTextChunk *chunk);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithFloat_withComItextpdfTextChunk_(jfloat leading, ComItextpdfTextChunk *chunk) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithFloat_withNSString_(ComItextpdfTextAnchor *self, jfloat leading, NSString *string);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithFloat_withNSString_(jfloat leading, NSString *string) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithFloat_withNSString_withComItextpdfTextFont_(ComItextpdfTextAnchor *self, jfloat leading, NSString *string, ComItextpdfTextFont *font);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithFloat_withNSString_withComItextpdfTextFont_(jfloat leading, NSString *string, ComItextpdfTextFont *font) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnchor_initWithComItextpdfTextPhrase_(ComItextpdfTextAnchor *self, ComItextpdfTextPhrase *phrase);

FOUNDATION_EXPORT ComItextpdfTextAnchor *new_ComItextpdfTextAnchor_initWithComItextpdfTextPhrase_(ComItextpdfTextPhrase *phrase) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextAnchor)

#endif // _ComItextpdfTextAnchor_H_
