//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/Annotation.java
//

#ifndef _ComItextpdfTextAnnotation_H_
#define _ComItextpdfTextAnnotation_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/Element.h"

@class JavaNetURL;
@class JavaUtilHashMap;
@protocol ComItextpdfTextElementListener;
@protocol JavaUtilList;

#define ComItextpdfTextAnnotation_TEXT 0
#define ComItextpdfTextAnnotation_URL_NET 1
#define ComItextpdfTextAnnotation_URL_AS_STRING 2
#define ComItextpdfTextAnnotation_FILE_DEST 3
#define ComItextpdfTextAnnotation_FILE_PAGE 4
#define ComItextpdfTextAnnotation_NAMED_DEST 5
#define ComItextpdfTextAnnotation_LAUNCH 6
#define ComItextpdfTextAnnotation_SCREEN 7

@interface ComItextpdfTextAnnotation : NSObject < ComItextpdfTextElement > {
 @public
  jint annotationtype_;
  JavaUtilHashMap *annotationAttributes_;
  jfloat llx__;
  jfloat lly__;
  jfloat urx__;
  jfloat ury__;
}

#pragma mark Public

- (instancetype)initWithComItextpdfTextAnnotation:(ComItextpdfTextAnnotation *)an;

- (instancetype)initWithFloat:(jfloat)llx
                    withFloat:(jfloat)lly
                    withFloat:(jfloat)urx
                    withFloat:(jfloat)ury
                      withInt:(jint)named;

- (instancetype)initWithFloat:(jfloat)llx
                    withFloat:(jfloat)lly
                    withFloat:(jfloat)urx
                    withFloat:(jfloat)ury
                 withNSString:(NSString *)url;

- (instancetype)initWithFloat:(jfloat)llx
                    withFloat:(jfloat)lly
                    withFloat:(jfloat)urx
                    withFloat:(jfloat)ury
                 withNSString:(NSString *)file
                      withInt:(jint)page;

- (instancetype)initWithFloat:(jfloat)llx
                    withFloat:(jfloat)lly
                    withFloat:(jfloat)urx
                    withFloat:(jfloat)ury
                 withNSString:(NSString *)file
                 withNSString:(NSString *)dest;

- (instancetype)initWithFloat:(jfloat)llx
                    withFloat:(jfloat)lly
                    withFloat:(jfloat)urx
                    withFloat:(jfloat)ury
                 withNSString:(NSString *)moviePath
                 withNSString:(NSString *)mimeType
                  withBoolean:(jboolean)showOnDisplay;

- (instancetype)initWithFloat:(jfloat)llx
                    withFloat:(jfloat)lly
                    withFloat:(jfloat)urx
                    withFloat:(jfloat)ury
                 withNSString:(NSString *)application
                 withNSString:(NSString *)parameters
                 withNSString:(NSString *)operation
                 withNSString:(NSString *)defaultdir;

- (instancetype)initWithFloat:(jfloat)llx
                    withFloat:(jfloat)lly
                    withFloat:(jfloat)urx
                    withFloat:(jfloat)ury
               withJavaNetURL:(JavaNetURL *)url;

- (instancetype)initWithNSString:(NSString *)title
                    withNSString:(NSString *)text;

- (instancetype)initWithNSString:(NSString *)title
                    withNSString:(NSString *)text
                       withFloat:(jfloat)llx
                       withFloat:(jfloat)lly
                       withFloat:(jfloat)urx
                       withFloat:(jfloat)ury;

- (jint)annotationType;

- (JavaUtilHashMap *)attributes;

- (NSString *)content;

- (id<JavaUtilList>)getChunks;

- (jboolean)isContent;

- (jboolean)isNestable;

- (jfloat)llx;

- (jfloat)llxWithFloat:(jfloat)def;

- (jfloat)lly;

- (jfloat)llyWithFloat:(jfloat)def;

- (jboolean)processWithComItextpdfTextElementListener:(id<ComItextpdfTextElementListener>)listener;

- (void)setDimensionsWithFloat:(jfloat)llx
                     withFloat:(jfloat)lly
                     withFloat:(jfloat)urx
                     withFloat:(jfloat)ury;

- (NSString *)title;

- (jint)type;

- (jfloat)urx;

- (jfloat)urxWithFloat:(jfloat)def;

- (jfloat)ury;

- (jfloat)uryWithFloat:(jfloat)def;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextAnnotation)

J2OBJC_FIELD_SETTER(ComItextpdfTextAnnotation, annotationAttributes_, JavaUtilHashMap *)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, TEXT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, URL_NET, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, URL_AS_STRING, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, FILE_DEST, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, FILE_PAGE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, NAMED_DEST, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, LAUNCH, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, SCREEN, jint)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_TITLE_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, TITLE_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_CONTENT_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, CONTENT_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_URL_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, URL_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_FILE__;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, FILE__, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_DESTINATION_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, DESTINATION_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_PAGE_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, PAGE_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_NAMED_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, NAMED_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_APPLICATION_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, APPLICATION_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_PARAMETERS_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, PARAMETERS_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_OPERATION_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, OPERATION_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_DEFAULTDIR_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, DEFAULTDIR_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_LLX_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, LLX_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_LLY_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, LLY_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_URX_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, URX_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_URY_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, URY_, NSString *)

FOUNDATION_EXPORT NSString *ComItextpdfTextAnnotation_MIMETYPE_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextAnnotation, MIMETYPE_, NSString *)

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithComItextpdfTextAnnotation_(ComItextpdfTextAnnotation *self, ComItextpdfTextAnnotation *an);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithComItextpdfTextAnnotation_(ComItextpdfTextAnnotation *an) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithNSString_withNSString_(ComItextpdfTextAnnotation *self, NSString *title, NSString *text);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithNSString_withNSString_(NSString *title, NSString *text) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithNSString_withNSString_withFloat_withFloat_withFloat_withFloat_(ComItextpdfTextAnnotation *self, NSString *title, NSString *text, jfloat llx, jfloat lly, jfloat urx, jfloat ury);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithNSString_withNSString_withFloat_withFloat_withFloat_withFloat_(NSString *title, NSString *text, jfloat llx, jfloat lly, jfloat urx, jfloat ury) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withJavaNetURL_(ComItextpdfTextAnnotation *self, jfloat llx, jfloat lly, jfloat urx, jfloat ury, JavaNetURL *url);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withJavaNetURL_(jfloat llx, jfloat lly, jfloat urx, jfloat ury, JavaNetURL *url) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_(ComItextpdfTextAnnotation *self, jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *url);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_(jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *url) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withNSString_(ComItextpdfTextAnnotation *self, jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *file, NSString *dest);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withNSString_(jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *file, NSString *dest) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withNSString_withBoolean_(ComItextpdfTextAnnotation *self, jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *moviePath, NSString *mimeType, jboolean showOnDisplay);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withNSString_withBoolean_(jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *moviePath, NSString *mimeType, jboolean showOnDisplay) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withInt_(ComItextpdfTextAnnotation *self, jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *file, jint page);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withInt_(jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *file, jint page) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withInt_(ComItextpdfTextAnnotation *self, jfloat llx, jfloat lly, jfloat urx, jfloat ury, jint named);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withInt_(jfloat llx, jfloat lly, jfloat urx, jfloat ury, jint named) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withNSString_withNSString_withNSString_(ComItextpdfTextAnnotation *self, jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *application, NSString *parameters, NSString *operation, NSString *defaultdir);

FOUNDATION_EXPORT ComItextpdfTextAnnotation *new_ComItextpdfTextAnnotation_initWithFloat_withFloat_withFloat_withFloat_withNSString_withNSString_withNSString_withNSString_(jfloat llx, jfloat lly, jfloat urx, jfloat ury, NSString *application, NSString *parameters, NSString *operation, NSString *defaultdir) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextAnnotation)

#endif // _ComItextpdfTextAnnotation_H_
