//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/ChapterAutoNumber.java
//

#ifndef _ComItextpdfTextChapterAutoNumber_H_
#define _ComItextpdfTextChapterAutoNumber_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/Chapter.h"

@class ComItextpdfTextParagraph;
@class ComItextpdfTextSection;

@interface ComItextpdfTextChapterAutoNumber : ComItextpdfTextChapter {
 @public
  jboolean numberSet_;
}

#pragma mark Public

- (instancetype)initWithComItextpdfTextParagraph:(ComItextpdfTextParagraph *)para;

- (instancetype)initWithNSString:(NSString *)title;

- (ComItextpdfTextSection *)addSectionWithComItextpdfTextParagraph:(ComItextpdfTextParagraph *)title;

- (ComItextpdfTextSection *)addSectionWithNSString:(NSString *)title;

- (jint)setAutomaticNumberWithInt:(jint)number;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextChapterAutoNumber)

FOUNDATION_EXPORT void ComItextpdfTextChapterAutoNumber_initWithComItextpdfTextParagraph_(ComItextpdfTextChapterAutoNumber *self, ComItextpdfTextParagraph *para);

FOUNDATION_EXPORT ComItextpdfTextChapterAutoNumber *new_ComItextpdfTextChapterAutoNumber_initWithComItextpdfTextParagraph_(ComItextpdfTextParagraph *para) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextChapterAutoNumber_initWithNSString_(ComItextpdfTextChapterAutoNumber *self, NSString *title);

FOUNDATION_EXPORT ComItextpdfTextChapterAutoNumber *new_ComItextpdfTextChapterAutoNumber_initWithNSString_(NSString *title) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextChapterAutoNumber)

#endif // _ComItextpdfTextChapterAutoNumber_H_
