//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/DocumentException.java
//

#ifndef _ComItextpdfTextDocumentException_H_
#define _ComItextpdfTextDocumentException_H_

#include "J2ObjC_header.h"
#include "java/lang/Exception.h"

@interface ComItextpdfTextDocumentException : JavaLangException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaLangException:(JavaLangException *)ex;

- (instancetype)initWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextDocumentException)

FOUNDATION_EXPORT void ComItextpdfTextDocumentException_initWithJavaLangException_(ComItextpdfTextDocumentException *self, JavaLangException *ex);

FOUNDATION_EXPORT ComItextpdfTextDocumentException *new_ComItextpdfTextDocumentException_initWithJavaLangException_(JavaLangException *ex) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextDocumentException_init(ComItextpdfTextDocumentException *self);

FOUNDATION_EXPORT ComItextpdfTextDocumentException *new_ComItextpdfTextDocumentException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextDocumentException_initWithNSString_(ComItextpdfTextDocumentException *self, NSString *message);

FOUNDATION_EXPORT ComItextpdfTextDocumentException *new_ComItextpdfTextDocumentException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextDocumentException)

#endif // _ComItextpdfTextDocumentException_H_
