//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/Header.java
//

#ifndef _ComItextpdfTextHeader_H_
#define _ComItextpdfTextHeader_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/Meta.h"

@interface ComItextpdfTextHeader : ComItextpdfTextMeta

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name
                    withNSString:(NSString *)content;

- (NSString *)getName;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextHeader)

FOUNDATION_EXPORT void ComItextpdfTextHeader_initWithNSString_withNSString_(ComItextpdfTextHeader *self, NSString *name, NSString *content);

FOUNDATION_EXPORT ComItextpdfTextHeader *new_ComItextpdfTextHeader_initWithNSString_withNSString_(NSString *name, NSString *content) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextHeader)

#endif // _ComItextpdfTextHeader_H_
