//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/ListItem.java
//

#ifndef _ComItextpdfTextListItem_H_
#define _ComItextpdfTextListItem_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/Paragraph.h"

@class ComItextpdfTextChunk;
@class ComItextpdfTextFont;
@class ComItextpdfTextListBody;
@class ComItextpdfTextListLabel;
@class ComItextpdfTextPhrase;

@interface ComItextpdfTextListItem : ComItextpdfTextParagraph {
 @public
  ComItextpdfTextChunk *symbol_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithComItextpdfTextChunk:(ComItextpdfTextChunk *)chunk;

- (instancetype)initWithFloat:(jfloat)leading;

- (instancetype)initWithFloat:(jfloat)leading
     withComItextpdfTextChunk:(ComItextpdfTextChunk *)chunk;

- (instancetype)initWithFloat:(jfloat)leading
                 withNSString:(NSString *)string;

- (instancetype)initWithFloat:(jfloat)leading
                 withNSString:(NSString *)string
      withComItextpdfTextFont:(ComItextpdfTextFont *)font;

- (instancetype)initWithComItextpdfTextPhrase:(ComItextpdfTextPhrase *)phrase;

- (instancetype)initWithNSString:(NSString *)string;

- (instancetype)initWithNSString:(NSString *)string
         withComItextpdfTextFont:(ComItextpdfTextFont *)font;

- (void)adjustListSymbolFont;

- (ComItextpdfTextListBody *)getListBody;

- (ComItextpdfTextListLabel *)getListLabel;

- (ComItextpdfTextChunk *)getListSymbol;

- (void)setIndentationLeftWithFloat:(jfloat)indentation
                        withBoolean:(jboolean)autoindent;

- (void)setListSymbolWithComItextpdfTextChunk:(ComItextpdfTextChunk *)symbol;

- (jint)type;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextListItem)

J2OBJC_FIELD_SETTER(ComItextpdfTextListItem, symbol_, ComItextpdfTextChunk *)

FOUNDATION_EXPORT void ComItextpdfTextListItem_init(ComItextpdfTextListItem *self);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithFloat_(ComItextpdfTextListItem *self, jfloat leading);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithFloat_(jfloat leading) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithComItextpdfTextChunk_(ComItextpdfTextListItem *self, ComItextpdfTextChunk *chunk);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithComItextpdfTextChunk_(ComItextpdfTextChunk *chunk) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithNSString_(ComItextpdfTextListItem *self, NSString *string);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithNSString_(NSString *string) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithNSString_withComItextpdfTextFont_(ComItextpdfTextListItem *self, NSString *string, ComItextpdfTextFont *font);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithNSString_withComItextpdfTextFont_(NSString *string, ComItextpdfTextFont *font) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithFloat_withComItextpdfTextChunk_(ComItextpdfTextListItem *self, jfloat leading, ComItextpdfTextChunk *chunk);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithFloat_withComItextpdfTextChunk_(jfloat leading, ComItextpdfTextChunk *chunk) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithFloat_withNSString_(ComItextpdfTextListItem *self, jfloat leading, NSString *string);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithFloat_withNSString_(jfloat leading, NSString *string) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithFloat_withNSString_withComItextpdfTextFont_(ComItextpdfTextListItem *self, jfloat leading, NSString *string, ComItextpdfTextFont *font);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithFloat_withNSString_withComItextpdfTextFont_(jfloat leading, NSString *string, ComItextpdfTextFont *font) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextListItem_initWithComItextpdfTextPhrase_(ComItextpdfTextListItem *self, ComItextpdfTextPhrase *phrase);

FOUNDATION_EXPORT ComItextpdfTextListItem *new_ComItextpdfTextListItem_initWithComItextpdfTextPhrase_(ComItextpdfTextPhrase *phrase) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextListItem)

#endif // _ComItextpdfTextListItem_H_
