//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/TabSplitCharacter.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/TabSplitCharacter.java"

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "com/itextpdf/text/SplitCharacter.h"
#include "com/itextpdf/text/TabSplitCharacter.h"

BOOL ComItextpdfTextTabSplitCharacter_initialized = NO;


#line 50
@implementation ComItextpdfTextTabSplitCharacter

id<ComItextpdfTextSplitCharacter> ComItextpdfTextTabSplitCharacter_TAB_;

- (jboolean)isSplitCharacterWithInt:(jint)start
                            withInt:(jint)current
                            withInt:(jint)end
                      withCharArray:(IOSCharArray *)cc
withComItextpdfTextPdfPdfChunkArray:(IOSObjectArray *)ck {
  
#line 55
  return YES;
}

- (instancetype)init {
  return [super init];
}

+ (void)initialize {
  if (self == [ComItextpdfTextTabSplitCharacter class]) {
    ComItextpdfTextTabSplitCharacter_TAB_ =
#line 52
    [[ComItextpdfTextTabSplitCharacter alloc] init];
    ComItextpdfTextTabSplitCharacter_initialized = YES;
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "isSplitCharacterWithInt:withInt:withInt:withCharArray:withComItextpdfTextPdfPdfChunkArray:", "isSplitCharacter", "Z", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "TAB_", NULL, 0x19, "Lcom.itextpdf.text.SplitCharacter;", &ComItextpdfTextTabSplitCharacter_TAB_,  },
  };
  static const J2ObjcClassInfo _ComItextpdfTextTabSplitCharacter = { "TabSplitCharacter", "com.itextpdf.text", NULL, 0x1, 2, methods, 1, fields, 0, NULL};
  return &_ComItextpdfTextTabSplitCharacter;
}

@end
