//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/WritableDirectElement.java
//

#ifndef _ComItextpdfTextWritableDirectElement_H_
#define _ComItextpdfTextWritableDirectElement_H_

@protocol ComItextpdfTextElementListener;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "com/itextpdf/text/Element.h"
#include "com/itextpdf/text/api/WriterOperation.h"

@interface ComItextpdfTextWritableDirectElement : NSObject < ComItextpdfTextElement, ComItextpdfTextApiWriterOperation > {
}

- (jboolean)processWithComItextpdfTextElementListener:(id<ComItextpdfTextElementListener>)listener;

- (jint)type;

- (jboolean)isContent;

- (jboolean)isNestable;

- (id<JavaUtilList>)getChunks;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComItextpdfTextWritableDirectElement_init() {}

#endif // _ComItextpdfTextWritableDirectElement_H_
