//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/api/Spaceable.java
//

#ifndef _ComItextpdfTextApiSpaceable_H_
#define _ComItextpdfTextApiSpaceable_H_

#include "J2ObjC_header.h"

@protocol ComItextpdfTextApiSpaceable < NSObject, JavaObject >

- (void)setSpacingBeforeWithFloat:(jfloat)spacing;

- (void)setSpacingAfterWithFloat:(jfloat)spacing;

- (jfloat)getSpacingBefore;

- (jfloat)getSpacingAfter;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextApiSpaceable)

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextApiSpaceable)

#endif // _ComItextpdfTextApiSpaceable_H_
