//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/log/NoOpLogger.java
//

#ifndef _ComItextpdfTextLogNoOpLogger_H_
#define _ComItextpdfTextLogNoOpLogger_H_

@class ComItextpdfTextLogLevelEnum;
@class IOSClass;
@class JavaLangException;

#import "JreEmulation.h"
#include "com/itextpdf/text/log/Logger.h"

@interface ComItextpdfTextLogNoOpLogger : NSObject < ComItextpdfTextLogLogger > {
}

- (id<ComItextpdfTextLogLogger>)getLoggerWithIOSClass:(IOSClass *)name;

- (void)warnWithNSString:(NSString *)message;

- (void)traceWithNSString:(NSString *)message;

- (void)debugWithNSString:(NSString *)message;

- (void)infoWithNSString:(NSString *)message;

- (void)errorWithNSString:(NSString *)message
    withJavaLangException:(JavaLangException *)e;

- (jboolean)isLoggingWithComItextpdfTextLogLevelEnum:(ComItextpdfTextLogLevelEnum *)level;

- (void)errorWithNSString:(NSString *)message;

- (id<ComItextpdfTextLogLogger>)getLoggerWithNSString:(NSString *)name;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComItextpdfTextLogNoOpLogger_init() {}

#endif // _ComItextpdfTextLogNoOpLogger_H_
