//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/log/NoOpCounter.java
//

#ifndef _ComItextpdfTextLogNoOpCounter_H_
#define _ComItextpdfTextLogNoOpCounter_H_

@class IOSClass;

#import "JreEmulation.h"
#include "com/itextpdf/text/log/Counter.h"

@interface ComItextpdfTextLogNoOpCounter : NSObject < ComItextpdfTextLogCounter > {
}

- (id<ComItextpdfTextLogCounter>)getCounterWithIOSClass:(IOSClass *)klass;

- (void)readWithLong:(jlong)l;

- (void)writtenWithLong:(jlong)l;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComItextpdfTextLogNoOpCounter_init() {}

#endif // _ComItextpdfTextLogNoOpCounter_H_
