//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/qrcode/BlockPair.java
//

#ifndef _ComItextpdfTextPdfQrcodeBlockPair_H_
#define _ComItextpdfTextPdfQrcodeBlockPair_H_

#include "J2ObjC_header.h"

@class ComItextpdfTextPdfQrcodeByteArray;

@interface ComItextpdfTextPdfQrcodeBlockPair : NSObject

#pragma mark Public

- (ComItextpdfTextPdfQrcodeByteArray *)getDataBytes;

- (ComItextpdfTextPdfQrcodeByteArray *)getErrorCorrectionBytes;

#pragma mark Package-Private

- (instancetype)initWithComItextpdfTextPdfQrcodeByteArray:(ComItextpdfTextPdfQrcodeByteArray *)data
                    withComItextpdfTextPdfQrcodeByteArray:(ComItextpdfTextPdfQrcodeByteArray *)errorCorrection;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfQrcodeBlockPair)

FOUNDATION_EXPORT void ComItextpdfTextPdfQrcodeBlockPair_initWithComItextpdfTextPdfQrcodeByteArray_withComItextpdfTextPdfQrcodeByteArray_(ComItextpdfTextPdfQrcodeBlockPair *self, ComItextpdfTextPdfQrcodeByteArray *data, ComItextpdfTextPdfQrcodeByteArray *errorCorrection);

FOUNDATION_EXPORT ComItextpdfTextPdfQrcodeBlockPair *new_ComItextpdfTextPdfQrcodeBlockPair_initWithComItextpdfTextPdfQrcodeByteArray_withComItextpdfTextPdfQrcodeByteArray_(ComItextpdfTextPdfQrcodeByteArray *data, ComItextpdfTextPdfQrcodeByteArray *errorCorrection) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfQrcodeBlockPair)

#endif // _ComItextpdfTextPdfQrcodeBlockPair_H_
