//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/impl/ByteBuffer.java
//

#ifndef _ComItextpdfXmpImplByteBuffer_H_
#define _ComItextpdfXmpImplByteBuffer_H_

#include "J2ObjC_header.h"

@class IOSByteArray;
@class JavaIoInputStream;

@interface ComItextpdfXmpImplByteBuffer : NSObject

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)buffer;

- (instancetype)initWithByteArray:(IOSByteArray *)buffer
                          withInt:(jint)length;

- (instancetype)initWithByteArray:(IOSByteArray *)buffer
                          withInt:(jint)offset
                          withInt:(jint)length;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (instancetype)initWithInt:(jint)initialCapacity;

- (void)appendWithByte:(jbyte)b;

- (void)appendWithByteArray:(IOSByteArray *)bytes;

- (void)appendWithByteArray:(IOSByteArray *)bytes
                    withInt:(jint)offset
                    withInt:(jint)len;

- (void)appendWithComItextpdfXmpImplByteBuffer:(ComItextpdfXmpImplByteBuffer *)anotherBuffer;

- (jbyte)byteAtWithInt:(jint)index;

- (jint)charAtWithInt:(jint)index;

- (JavaIoInputStream *)getByteStream;

- (NSString *)getEncoding;

- (jint)length;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfXmpImplByteBuffer)

FOUNDATION_EXPORT void ComItextpdfXmpImplByteBuffer_initWithInt_(ComItextpdfXmpImplByteBuffer *self, jint initialCapacity);

FOUNDATION_EXPORT ComItextpdfXmpImplByteBuffer *new_ComItextpdfXmpImplByteBuffer_initWithInt_(jint initialCapacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfXmpImplByteBuffer_initWithByteArray_(ComItextpdfXmpImplByteBuffer *self, IOSByteArray *buffer);

FOUNDATION_EXPORT ComItextpdfXmpImplByteBuffer *new_ComItextpdfXmpImplByteBuffer_initWithByteArray_(IOSByteArray *buffer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfXmpImplByteBuffer_initWithByteArray_withInt_(ComItextpdfXmpImplByteBuffer *self, IOSByteArray *buffer, jint length);

FOUNDATION_EXPORT ComItextpdfXmpImplByteBuffer *new_ComItextpdfXmpImplByteBuffer_initWithByteArray_withInt_(IOSByteArray *buffer, jint length) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfXmpImplByteBuffer_initWithJavaIoInputStream_(ComItextpdfXmpImplByteBuffer *self, JavaIoInputStream *inArg);

FOUNDATION_EXPORT ComItextpdfXmpImplByteBuffer *new_ComItextpdfXmpImplByteBuffer_initWithJavaIoInputStream_(JavaIoInputStream *inArg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfXmpImplByteBuffer_initWithByteArray_withInt_withInt_(ComItextpdfXmpImplByteBuffer *self, IOSByteArray *buffer, jint offset, jint length);

FOUNDATION_EXPORT ComItextpdfXmpImplByteBuffer *new_ComItextpdfXmpImplByteBuffer_initWithByteArray_withInt_withInt_(IOSByteArray *buffer, jint offset, jint length) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfXmpImplByteBuffer)

#endif // _ComItextpdfXmpImplByteBuffer_H_
