//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/awt/geom/Dimension.java
//

#ifndef _ComItextpdfAwtGeomDimension_H_
#define _ComItextpdfAwtGeomDimension_H_

#import "JreEmulation.h"
#include "com/itextpdf/awt/geom/Dimension2D.h"
#include "java/io/Serializable.h"

#define ComItextpdfAwtGeomDimension_serialVersionUID 4723952579491349524LL

@interface ComItextpdfAwtGeomDimension : ComItextpdfAwtGeomDimension2D < JavaIoSerializable > {
 @public
  jdouble width_;
  jdouble height_;
}

- (instancetype)initWithComItextpdfAwtGeomDimension:(ComItextpdfAwtGeomDimension *)d;

- (instancetype)init;

- (instancetype)initWithDouble:(jdouble)width
                    withDouble:(jdouble)height;

- (instancetype)initWithInt:(jint)width
                    withInt:(jint)height;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

- (NSString *)description;

- (void)setSizeWithInt:(jint)width
               withInt:(jint)height;

- (void)setSizeWithComItextpdfAwtGeomDimension:(ComItextpdfAwtGeomDimension *)d;

- (void)setSizeWithDouble:(jdouble)width
               withDouble:(jdouble)height;

- (ComItextpdfAwtGeomDimension *)getSize;

- (jdouble)getHeight;

- (jdouble)getWidth;

- (void)copyAllFieldsTo:(ComItextpdfAwtGeomDimension *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfAwtGeomDimension_init() {}

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomDimension, serialVersionUID, jlong)

#endif // _ComItextpdfAwtGeomDimension_H_
