//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/awt/geom/FlatteningPathIterator.java
//

#ifndef _ComItextpdfAwtGeomFlatteningPathIterator_H_
#define _ComItextpdfAwtGeomFlatteningPathIterator_H_

@class IOSDoubleArray;
@class IOSFloatArray;

#import "JreEmulation.h"
#include "com/itextpdf/awt/geom/PathIterator.h"

#define ComItextpdfAwtGeomFlatteningPathIterator_BUFFER_CAPACITY 16
#define ComItextpdfAwtGeomFlatteningPathIterator_BUFFER_LIMIT 16
#define ComItextpdfAwtGeomFlatteningPathIterator_BUFFER_SIZE 16

@interface ComItextpdfAwtGeomFlatteningPathIterator : NSObject < ComItextpdfAwtGeomPathIterator > {
 @public
  jint bufType_;
  jint bufLimit_;
  jint bufSize_;
  jint bufIndex_;
  jint bufSubdiv_;
  IOSDoubleArray *buf_;
  jboolean bufEmpty_;
  id<ComItextpdfAwtGeomPathIterator> p_;
  jdouble flatness_;
  jdouble flatness2_;
  jdouble px_;
  jdouble py_;
  IOSDoubleArray *coords_;
}

- (instancetype)initWithComItextpdfAwtGeomPathIterator:(id<ComItextpdfAwtGeomPathIterator>)path
                                            withDouble:(jdouble)flatness;

- (instancetype)initWithComItextpdfAwtGeomPathIterator:(id<ComItextpdfAwtGeomPathIterator>)path
                                            withDouble:(jdouble)flatness
                                               withInt:(jint)limit;

- (jdouble)getFlatness;

- (jint)getRecursionLimit;

- (jint)getWindingRule;

- (jboolean)isDone;

- (void)evaluate;

- (void)next;

- (jint)currentSegmentWithFloatArray:(IOSFloatArray *)coords;

- (jint)currentSegmentWithDoubleArray:(IOSDoubleArray *)coords;

- (void)copyAllFieldsTo:(ComItextpdfAwtGeomFlatteningPathIterator *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfAwtGeomFlatteningPathIterator_init() {}

J2OBJC_FIELD_SETTER(ComItextpdfAwtGeomFlatteningPathIterator, buf_, IOSDoubleArray *)
J2OBJC_FIELD_SETTER(ComItextpdfAwtGeomFlatteningPathIterator, p_, id<ComItextpdfAwtGeomPathIterator>)
J2OBJC_FIELD_SETTER(ComItextpdfAwtGeomFlatteningPathIterator, coords_, IOSDoubleArray *)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomFlatteningPathIterator, BUFFER_SIZE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomFlatteningPathIterator, BUFFER_LIMIT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfAwtGeomFlatteningPathIterator, BUFFER_CAPACITY, jint)

#endif // _ComItextpdfAwtGeomFlatteningPathIterator_H_
