//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/awt/geom/PathIterator.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/awt/geom/PathIterator.java"

#include "IOSPrimitiveArray.h"
#include "com/itextpdf/awt/geom/PathIterator.h"

@interface ComItextpdfAwtGeomPathIterator : NSObject
@end

@implementation ComItextpdfAwtGeomPathIterator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getWindingRule", NULL, "I", 0x401, NULL },
    { "isDone", NULL, "Z", 0x401, NULL },
    { "next", NULL, "V", 0x401, NULL },
    { "currentSegmentWithFloatArray:", "currentSegment", "I", 0x401, NULL },
    { "currentSegmentWithDoubleArray:", "currentSegment", "I", 0x401, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "WIND_EVEN_ODD_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfAwtGeomPathIterator_WIND_EVEN_ODD },
    { "WIND_NON_ZERO_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfAwtGeomPathIterator_WIND_NON_ZERO },
    { "SEG_MOVETO_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfAwtGeomPathIterator_SEG_MOVETO },
    { "SEG_LINETO_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfAwtGeomPathIterator_SEG_LINETO },
    { "SEG_QUADTO_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfAwtGeomPathIterator_SEG_QUADTO },
    { "SEG_CUBICTO_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfAwtGeomPathIterator_SEG_CUBICTO },
    { "SEG_CLOSE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfAwtGeomPathIterator_SEG_CLOSE },
  };
  static const J2ObjcClassInfo _ComItextpdfAwtGeomPathIterator = { "PathIterator", "com.itextpdf.awt.geom", NULL, 0x201, 5, methods, 7, fields, 0, NULL};
  return &_ComItextpdfAwtGeomPathIterator;
}

@end

