//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/XMPError.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/XMPError.java"

#include "com/itextpdf/xmp/XMPError.h"

@interface ComItextpdfXmpXMPError : NSObject
@end

@implementation ComItextpdfXmpXMPError

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "UNKNOWN_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_UNKNOWN },
    { "BADPARAM_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADPARAM },
    { "BADVALUE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADVALUE },
    { "INTERNALFAILURE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_INTERNALFAILURE },
    { "BADSCHEMA_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADSCHEMA },
    { "BADXPATH_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADXPATH },
    { "BADOPTIONS_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADOPTIONS },
    { "BADINDEX_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADINDEX },
    { "BADSERIALIZE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADSERIALIZE },
    { "BADXML_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADXML },
    { "BADRDF_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADRDF },
    { "BADXMP_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADXMP },
    { "BADSTREAM_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComItextpdfXmpXMPError_BADSTREAM },
  };
  static const J2ObjcClassInfo _ComItextpdfXmpXMPError = { "XMPError", "com.itextpdf.xmp", NULL, 0x201, 0, NULL, 13, fields, 0, NULL};
  return &_ComItextpdfXmpXMPError;
}

@end

