//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/XMPMetaFactory.java
//

#ifndef _ComItextpdfXmpXMPMetaFactory_H_
#define _ComItextpdfXmpXMPMetaFactory_H_

#include "J2ObjC_header.h"

@class ComItextpdfXmpOptionsParseOptions;
@class ComItextpdfXmpOptionsSerializeOptions;
@class IOSByteArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol ComItextpdfXmpXMPMeta;
@protocol ComItextpdfXmpXMPSchemaRegistry;
@protocol ComItextpdfXmpXMPVersionInfo;

@interface ComItextpdfXmpXMPMetaFactory : NSObject

#pragma mark Public

+ (id<ComItextpdfXmpXMPMeta>)create;

+ (id<ComItextpdfXmpXMPSchemaRegistry>)getSchemaRegistry;

+ (id<ComItextpdfXmpXMPVersionInfo>)getVersionInfo;

+ (id<ComItextpdfXmpXMPMeta>)parseWithJavaIoInputStream:(JavaIoInputStream *)inArg;

+ (id<ComItextpdfXmpXMPMeta>)parseWithJavaIoInputStream:(JavaIoInputStream *)inArg
                  withComItextpdfXmpOptionsParseOptions:(ComItextpdfXmpOptionsParseOptions *)options;

+ (id<ComItextpdfXmpXMPMeta>)parseFromBufferWithByteArray:(IOSByteArray *)buffer;

+ (id<ComItextpdfXmpXMPMeta>)parseFromBufferWithByteArray:(IOSByteArray *)buffer
                    withComItextpdfXmpOptionsParseOptions:(ComItextpdfXmpOptionsParseOptions *)options;

+ (id<ComItextpdfXmpXMPMeta>)parseFromStringWithNSString:(NSString *)packet;

+ (id<ComItextpdfXmpXMPMeta>)parseFromStringWithNSString:(NSString *)packet
                   withComItextpdfXmpOptionsParseOptions:(ComItextpdfXmpOptionsParseOptions *)options;

+ (void)reset;

+ (void)serializeWithComItextpdfXmpXMPMeta:(id<ComItextpdfXmpXMPMeta>)xmp
                    withJavaIoOutputStream:(JavaIoOutputStream *)outArg;

+ (void)serializeWithComItextpdfXmpXMPMeta:(id<ComItextpdfXmpXMPMeta>)xmp
                    withJavaIoOutputStream:(JavaIoOutputStream *)outArg
 withComItextpdfXmpOptionsSerializeOptions:(ComItextpdfXmpOptionsSerializeOptions *)options;

+ (IOSByteArray *)serializeToBufferWithComItextpdfXmpXMPMeta:(id<ComItextpdfXmpXMPMeta>)xmp
                   withComItextpdfXmpOptionsSerializeOptions:(ComItextpdfXmpOptionsSerializeOptions *)options;

+ (NSString *)serializeToStringWithComItextpdfXmpXMPMeta:(id<ComItextpdfXmpXMPMeta>)xmp
               withComItextpdfXmpOptionsSerializeOptions:(ComItextpdfXmpOptionsSerializeOptions *)options;

@end

J2OBJC_STATIC_INIT(ComItextpdfXmpXMPMetaFactory)

FOUNDATION_EXPORT id<ComItextpdfXmpXMPSchemaRegistry> ComItextpdfXmpXMPMetaFactory_getSchemaRegistry();

FOUNDATION_EXPORT id<ComItextpdfXmpXMPMeta> ComItextpdfXmpXMPMetaFactory_create();

FOUNDATION_EXPORT id<ComItextpdfXmpXMPMeta> ComItextpdfXmpXMPMetaFactory_parseWithJavaIoInputStream_(JavaIoInputStream *inArg);

FOUNDATION_EXPORT id<ComItextpdfXmpXMPMeta> ComItextpdfXmpXMPMetaFactory_parseWithJavaIoInputStream_withComItextpdfXmpOptionsParseOptions_(JavaIoInputStream *inArg, ComItextpdfXmpOptionsParseOptions *options);

FOUNDATION_EXPORT id<ComItextpdfXmpXMPMeta> ComItextpdfXmpXMPMetaFactory_parseFromStringWithNSString_(NSString *packet);

FOUNDATION_EXPORT id<ComItextpdfXmpXMPMeta> ComItextpdfXmpXMPMetaFactory_parseFromStringWithNSString_withComItextpdfXmpOptionsParseOptions_(NSString *packet, ComItextpdfXmpOptionsParseOptions *options);

FOUNDATION_EXPORT id<ComItextpdfXmpXMPMeta> ComItextpdfXmpXMPMetaFactory_parseFromBufferWithByteArray_(IOSByteArray *buffer);

FOUNDATION_EXPORT id<ComItextpdfXmpXMPMeta> ComItextpdfXmpXMPMetaFactory_parseFromBufferWithByteArray_withComItextpdfXmpOptionsParseOptions_(IOSByteArray *buffer, ComItextpdfXmpOptionsParseOptions *options);

FOUNDATION_EXPORT void ComItextpdfXmpXMPMetaFactory_serializeWithComItextpdfXmpXMPMeta_withJavaIoOutputStream_(id<ComItextpdfXmpXMPMeta> xmp, JavaIoOutputStream *outArg);

FOUNDATION_EXPORT void ComItextpdfXmpXMPMetaFactory_serializeWithComItextpdfXmpXMPMeta_withJavaIoOutputStream_withComItextpdfXmpOptionsSerializeOptions_(id<ComItextpdfXmpXMPMeta> xmp, JavaIoOutputStream *outArg, ComItextpdfXmpOptionsSerializeOptions *options);

FOUNDATION_EXPORT IOSByteArray *ComItextpdfXmpXMPMetaFactory_serializeToBufferWithComItextpdfXmpXMPMeta_withComItextpdfXmpOptionsSerializeOptions_(id<ComItextpdfXmpXMPMeta> xmp, ComItextpdfXmpOptionsSerializeOptions *options);

FOUNDATION_EXPORT NSString *ComItextpdfXmpXMPMetaFactory_serializeToStringWithComItextpdfXmpXMPMeta_withComItextpdfXmpOptionsSerializeOptions_(id<ComItextpdfXmpXMPMeta> xmp, ComItextpdfXmpOptionsSerializeOptions *options);

FOUNDATION_EXPORT void ComItextpdfXmpXMPMetaFactory_reset();

FOUNDATION_EXPORT id<ComItextpdfXmpXMPVersionInfo> ComItextpdfXmpXMPMetaFactory_getVersionInfo();

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfXmpXMPMetaFactory)

#endif // _ComItextpdfXmpXMPMetaFactory_H_
