//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/XMPSchemaRegistry.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/XMPSchemaRegistry.java"

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/itextpdf/xmp/XMPException.h"
#include "com/itextpdf/xmp/XMPSchemaRegistry.h"
#include "com/itextpdf/xmp/properties/XMPAliasInfo.h"
#include "java/util/Map.h"

@interface ComItextpdfXmpXMPSchemaRegistry : NSObject
@end

@implementation ComItextpdfXmpXMPSchemaRegistry

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "registerNamespaceWithNSString:withNSString:", "registerNamespace", "Ljava.lang.String;", 0x401, "Lcom.itextpdf.xmp.XMPException;" },
    { "getNamespacePrefixWithNSString:", "getNamespacePrefix", "Ljava.lang.String;", 0x401, NULL },
    { "getNamespaceURIWithNSString:", "getNamespaceURI", "Ljava.lang.String;", 0x401, NULL },
    { "getNamespaces", NULL, "Ljava.util.Map;", 0x401, NULL },
    { "getPrefixes", NULL, "Ljava.util.Map;", 0x401, NULL },
    { "deleteNamespaceWithNSString:", "deleteNamespace", "V", 0x401, NULL },
    { "resolveAliasWithNSString:withNSString:", "resolveAlias", "Lcom.itextpdf.xmp.properties.XMPAliasInfo;", 0x401, NULL },
    { "findAliasesWithNSString:", "findAliases", "[Lcom.itextpdf.xmp.properties.XMPAliasInfo;", 0x401, NULL },
    { "findAliasWithNSString:", "findAlias", "Lcom.itextpdf.xmp.properties.XMPAliasInfo;", 0x401, NULL },
    { "getAliases", NULL, "Ljava.util.Map;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComItextpdfXmpXMPSchemaRegistry = { "XMPSchemaRegistry", "com.itextpdf.xmp", NULL, 0x201, 10, methods, 0, NULL, 0, NULL};
  return &_ComItextpdfXmpXMPSchemaRegistry;
}

@end

