//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/xml/simpleparser/handler/NeverNewLineHandler.java
//

#ifndef _ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler_H_
#define _ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/xml/simpleparser/NewLineHandler.h"

@interface ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler : NSObject < ComItextpdfTextXmlSimpleparserNewLineHandler >

#pragma mark Public

- (instancetype)init;

- (jboolean)isNewLineTagWithNSString:(NSString *)tag;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler)

FOUNDATION_EXPORT void ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler_init(ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler *self);

FOUNDATION_EXPORT ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler *new_ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler)

#endif // _ComItextpdfTextXmlSimpleparserHandlerNeverNewLineHandler_H_
