//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/parser/RenderFilter.java
//

#ifndef _ComItextpdfTextPdfParserRenderFilter_H_
#define _ComItextpdfTextPdfParserRenderFilter_H_

@class ComItextpdfTextPdfParserImageRenderInfo;
@class ComItextpdfTextPdfParserTextRenderInfo;

#import "JreEmulation.h"

@interface ComItextpdfTextPdfParserRenderFilter : NSObject {
}

- (jboolean)allowTextWithComItextpdfTextPdfParserTextRenderInfo:(ComItextpdfTextPdfParserTextRenderInfo *)renderInfo;

- (jboolean)allowImageWithComItextpdfTextPdfParserImageRenderInfo:(ComItextpdfTextPdfParserImageRenderInfo *)renderInfo;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfParserRenderFilter_init() {}

#endif // _ComItextpdfTextPdfParserRenderFilter_H_
