//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/fonts/cmaps/CidResource.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/fonts/cmaps/CidResource.java"

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/itextpdf/text/error_messages/MessageLocalization.h"
#include "com/itextpdf/text/io/RandomAccessSource.h"
#include "com/itextpdf/text/io/RandomAccessSourceFactory.h"
#include "com/itextpdf/text/io/StreamUtil.h"
#include "com/itextpdf/text/pdf/BaseFont.h"
#include "com/itextpdf/text/pdf/PRTokeniser.h"
#include "com/itextpdf/text/pdf/RandomAccessFileOrArray.h"
#include "com/itextpdf/text/pdf/fonts/cmaps/CidResource.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"


#line 61
@implementation ComItextpdfTextPdfFontsCmapsCidResource

- (ComItextpdfTextPdfPRTokeniser *)getLocationWithNSString:(NSString *)location {
  
#line 64
  NSString *fullName = JreStrcat("$$$", ComItextpdfTextPdfBaseFont_get_RESOURCE_PATH_(), @"cmaps/", location);
  JavaIoInputStream *inp = [ComItextpdfTextIoStreamUtil getResourceStreamWithNSString:fullName];
  if (inp == nil)
#line 67
  @throw [[JavaIoIOException alloc] initWithNSString:[ComItextpdfTextError_messagesMessageLocalization getComposedMessageWithNSString:@"the.cmap.1.was.not.found" withNSObjectArray:[IOSObjectArray arrayWithObjects:(id[]){ fullName } count:1 type:[IOSClass classWithClass:[NSObject class]]]]];
  return [[ComItextpdfTextPdfPRTokeniser alloc] initWithComItextpdfTextPdfRandomAccessFileOrArray:[[ComItextpdfTextPdfRandomAccessFileOrArray alloc] initWithComItextpdfTextIoRandomAccessSource:[((ComItextpdfTextIoRandomAccessSourceFactory *) [[ComItextpdfTextIoRandomAccessSourceFactory alloc] init]) createSourceWithJavaIoInputStream:inp]]];
}

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getLocationWithNSString:", "getLocation", "Lcom.itextpdf.text.pdf.PRTokeniser;", 0x1, "Ljava.io.IOException;" },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcClassInfo _ComItextpdfTextPdfFontsCmapsCidResource = { "CidResource", "com.itextpdf.text.pdf.fonts.cmaps", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_ComItextpdfTextPdfFontsCmapsCidResource;
}

@end
