//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/properties/XMPAliasInfo.java
//

#ifndef _ComItextpdfXmpPropertiesXMPAliasInfo_H_
#define _ComItextpdfXmpPropertiesXMPAliasInfo_H_

@class ComItextpdfXmpOptionsAliasOptions;

#import "JreEmulation.h"

@protocol ComItextpdfXmpPropertiesXMPAliasInfo < NSObject, JavaObject >

- (NSString *)getNamespace;

- (NSString *)getPrefix;

- (NSString *)getPropName;

- (ComItextpdfXmpOptionsAliasOptions *)getAliasForm;

@end

__attribute__((always_inline)) inline void ComItextpdfXmpPropertiesXMPAliasInfo_init() {}

#endif // _ComItextpdfXmpPropertiesXMPAliasInfo_H_
