//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/properties/XMPAliasInfo.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/xmp/properties/XMPAliasInfo.java"

#include "com/itextpdf/xmp/options/AliasOptions.h"
#include "com/itextpdf/xmp/properties/XMPAliasInfo.h"

@interface ComItextpdfXmpPropertiesXMPAliasInfo : NSObject
@end

@implementation ComItextpdfXmpPropertiesXMPAliasInfo

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getNamespace", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "getPrefix", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "getPropName", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "getAliasForm", NULL, "Lcom.itextpdf.xmp.options.AliasOptions;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComItextpdfXmpPropertiesXMPAliasInfo = { "XMPAliasInfo", "com.itextpdf.xmp.properties", NULL, 0x201, 4, methods, 0, NULL, 0, NULL};
  return &_ComItextpdfXmpPropertiesXMPAliasInfo;
}

@end

