//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/xml/xmp/XmpMMProperties.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/xml/xmp/XmpMMProperties.java"

#include "com/itextpdf/text/xml/xmp/XmpMMProperties.h"


#line 47
@implementation ComItextpdfTextXmlXmpXmpMMProperties

NSString * ComItextpdfTextXmlXmpXmpMMProperties_DERIVEDFROM_ = @"DerivedFrom";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_DOCUMENTID_ = 
#line 51
@"DocumentID";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_HISTORY_ = @"History";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_MANAGEDFROM_ = 
#line 55
@"ManagedFrom";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_MANAGER_ = @"Manager";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_MANAGETO_ = 
#line 59
@"ManageTo";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_MANAGEUI_ = @"ManageUI";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_MANAGERVARIANT_ = 
#line 63
@"ManagerVariant";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_RENDITIONCLASS_ = @"RenditionClass";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_RENDITIONPARAMS_ = 
#line 67
@"RenditionParams";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_VERSIONID_ = @"VersionID";
NSString * ComItextpdfTextXmlXmpXmpMMProperties_VERSIONS_ = 
#line 71
@"Versions";

- (instancetype)init {
  return [super init];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "DERIVEDFROM_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_DERIVEDFROM_,  },
    { "DOCUMENTID_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_DOCUMENTID_,  },
    { "HISTORY_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_HISTORY_,  },
    { "MANAGEDFROM_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_MANAGEDFROM_,  },
    { "MANAGER_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_MANAGER_,  },
    { "MANAGETO_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_MANAGETO_,  },
    { "MANAGEUI_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_MANAGEUI_,  },
    { "MANAGERVARIANT_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_MANAGERVARIANT_,  },
    { "RENDITIONCLASS_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_RENDITIONCLASS_,  },
    { "RENDITIONPARAMS_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_RENDITIONPARAMS_,  },
    { "VERSIONID_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_VERSIONID_,  },
    { "VERSIONS_", NULL, 0x19, "Ljava.lang.String;", &ComItextpdfTextXmlXmpXmpMMProperties_VERSIONS_,  },
  };
  static const J2ObjcClassInfo _ComItextpdfTextXmlXmpXmpMMProperties = { "XmpMMProperties", "com.itextpdf.text.xml.xmp", NULL, 0x1, 1, methods, 12, fields, 0, NULL};
  return &_ComItextpdfTextXmlXmpXmpMMProperties;
}

@end
