//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/BarcodeCodabar.java
//

#ifndef _ComItextpdfTextPdfBarcodeCodabar_H_
#define _ComItextpdfTextPdfBarcodeCodabar_H_

#include "J2ObjC_header.h"
#include "com/itextpdf/text/pdf/Barcode.h"

@class ComItextpdfTextBaseColor;
@class ComItextpdfTextPdfPdfContentByte;
@class ComItextpdfTextRectangle;
@class IOSByteArray;

@interface ComItextpdfTextPdfBarcodeCodabar : ComItextpdfTextPdfBarcode

#pragma mark Public

- (instancetype)init;

+ (NSString *)calculateChecksumWithNSString:(NSString *)code;

- (ComItextpdfTextRectangle *)getBarcodeSize;

+ (IOSByteArray *)getBarsCodabarWithNSString:(NSString *)text;

- (ComItextpdfTextRectangle *)placeBarcodeWithComItextpdfTextPdfPdfContentByte:(ComItextpdfTextPdfPdfContentByte *)cb
                                                  withComItextpdfTextBaseColor:(ComItextpdfTextBaseColor *)barColor
                                                  withComItextpdfTextBaseColor:(ComItextpdfTextBaseColor *)textColor;

@end

J2OBJC_STATIC_INIT(ComItextpdfTextPdfBarcodeCodabar)

FOUNDATION_EXPORT void ComItextpdfTextPdfBarcodeCodabar_init(ComItextpdfTextPdfBarcodeCodabar *self);

FOUNDATION_EXPORT ComItextpdfTextPdfBarcodeCodabar *new_ComItextpdfTextPdfBarcodeCodabar_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IOSByteArray *ComItextpdfTextPdfBarcodeCodabar_getBarsCodabarWithNSString_(NSString *text);

FOUNDATION_EXPORT NSString *ComItextpdfTextPdfBarcodeCodabar_calculateChecksumWithNSString_(NSString *code);

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfBarcodeCodabar)

#endif // _ComItextpdfTextPdfBarcodeCodabar_H_
