//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/BidiLine.java
//

#ifndef _ComItextpdfTextPdfBidiLine_H_
#define _ComItextpdfTextPdfBidiLine_H_

@class ComItextpdfTextPdfIntHashtable;
@class ComItextpdfTextPdfPdfChunk;
@class ComItextpdfTextPdfPdfLine;
@class IOSByteArray;
@class IOSCharArray;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaUtilArrayList;

#import "JreEmulation.h"

@interface ComItextpdfTextPdfBidiLine : NSObject {
 @public
  jint runDirection_;
  jint pieceSize_;
  IOSCharArray *text_;
  IOSObjectArray *detailChunks_;
  jint totalTextLength_;
  IOSByteArray *orderLevels_;
  IOSIntArray *indexChars_;
  JavaUtilArrayList *chunks_;
  jint indexChunk_;
  jint indexChunkChar_;
  jint currentChar_;
  jint storedRunDirection_;
  IOSCharArray *storedText_;
  IOSObjectArray *storedDetailChunks_;
  jint storedTotalTextLength_;
  IOSByteArray *storedOrderLevels_;
  IOSIntArray *storedIndexChars_;
  jint storedIndexChunk_;
  jint storedIndexChunkChar_;
  jint storedCurrentChar_;
  jboolean shortStore_;
  jint arabicOptions_;
}

- (instancetype)init;

- (instancetype)initWithComItextpdfTextPdfBidiLine:(ComItextpdfTextPdfBidiLine *)org;

- (jboolean)isEmpty;

- (void)clearChunks;

- (jboolean)getParagraphWithInt:(jint)runDirection;

- (void)addChunkWithComItextpdfTextPdfPdfChunk:(ComItextpdfTextPdfPdfChunk *)chunk;

- (void)addChunksWithJavaUtilArrayList:(JavaUtilArrayList *)chunks;

- (void)addPieceWithChar:(jchar)c
withComItextpdfTextPdfPdfChunk:(ComItextpdfTextPdfPdfChunk *)chunk;

- (void)save;

- (void)restore;

- (void)mirrorGlyphs;

- (void)doArabicShapping;

- (ComItextpdfTextPdfPdfLine *)processLineWithFloat:(jfloat)leftX
                                          withFloat:(jfloat)width
                                            withInt:(jint)alignment
                                            withInt:(jint)runDirection
                                            withInt:(jint)arabicOptions
                                          withFloat:(jfloat)minY
                                          withFloat:(jfloat)yLine
                                          withFloat:(jfloat)descender;

- (jfloat)getWidthWithInt:(jint)startIdx
                  withInt:(jint)lastIdx;

- (JavaUtilArrayList *)createArrayOfPdfChunksWithInt:(jint)startIdx
                                             withInt:(jint)endIdx;

- (JavaUtilArrayList *)createArrayOfPdfChunksWithInt:(jint)startIdx
                                             withInt:(jint)endIdx
                      withComItextpdfTextPdfPdfChunk:(ComItextpdfTextPdfPdfChunk *)extraPdfChunk;

- (IOSIntArray *)getWordWithInt:(jint)startIdx
                        withInt:(jint)idx;

- (jint)trimRightWithInt:(jint)startIdx
                 withInt:(jint)endIdx;

- (jint)trimLeftWithInt:(jint)startIdx
                withInt:(jint)endIdx;

- (jint)trimRightExWithInt:(jint)startIdx
                   withInt:(jint)endIdx;

- (jint)trimLeftExWithInt:(jint)startIdx
                  withInt:(jint)endIdx;

- (void)reorderWithInt:(jint)start
               withInt:(jint)end;

- (void)flipWithInt:(jint)start
            withInt:(jint)end;

+ (jboolean)isWSWithChar:(jchar)c;

+ (NSString *)processLTRWithNSString:(NSString *)s
                             withInt:(jint)runDirection
                             withInt:(jint)arabicOptions;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfBidiLine *)other;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextPdfBidiLine_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextPdfBidiLine)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, text_, IOSCharArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, detailChunks_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, orderLevels_, IOSByteArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, indexChars_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, chunks_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, storedText_, IOSCharArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, storedDetailChunks_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, storedOrderLevels_, IOSByteArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfBidiLine, storedIndexChars_, IOSIntArray *)

FOUNDATION_EXPORT ComItextpdfTextPdfIntHashtable *ComItextpdfTextPdfBidiLine_mirrorChars_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfBidiLine, mirrorChars_, ComItextpdfTextPdfIntHashtable *)

#endif // _ComItextpdfTextPdfBidiLine_H_
