//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/DefaultSplitCharacter.java
//

#ifndef _ComItextpdfTextPdfDefaultSplitCharacter_H_
#define _ComItextpdfTextPdfDefaultSplitCharacter_H_

@class IOSCharArray;
@class IOSObjectArray;

#import "JreEmulation.h"
#include "com/itextpdf/text/SplitCharacter.h"

@interface ComItextpdfTextPdfDefaultSplitCharacter : NSObject < ComItextpdfTextSplitCharacter > {
 @public
  IOSCharArray *characters_;
}

- (instancetype)init;

- (instancetype)initWithChar:(jchar)character;

- (instancetype)initWithCharArray:(IOSCharArray *)characters;

- (jboolean)isSplitCharacterWithInt:(jint)start
                            withInt:(jint)current
                            withInt:(jint)end
                      withCharArray:(IOSCharArray *)cc
withComItextpdfTextPdfPdfChunkArray:(IOSObjectArray *)ck;

- (jchar)getCurrentCharacterWithInt:(jint)current
                      withCharArray:(IOSCharArray *)cc
withComItextpdfTextPdfPdfChunkArray:(IOSObjectArray *)ck;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfDefaultSplitCharacter *)other;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextPdfDefaultSplitCharacter_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextPdfDefaultSplitCharacter)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfDefaultSplitCharacter, characters_, IOSCharArray *)

FOUNDATION_EXPORT id<ComItextpdfTextSplitCharacter> ComItextpdfTextPdfDefaultSplitCharacter_DEFAULT_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfDefaultSplitCharacter, DEFAULT_, id<ComItextpdfTextSplitCharacter>)

#endif // _ComItextpdfTextPdfDefaultSplitCharacter_H_
