//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/OutputStreamEncryption.java
//

#ifndef _ComItextpdfTextPdfOutputStreamEncryption_H_
#define _ComItextpdfTextPdfOutputStreamEncryption_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/io/OutputStream.h"

#define ComItextpdfTextPdfOutputStreamEncryption_AES_128 4
#define ComItextpdfTextPdfOutputStreamEncryption_AES_256 5

@interface ComItextpdfTextPdfOutputStreamEncryption : JavaIoOutputStream {
 @public
  JavaIoOutputStream *out_;
  IOSByteArray *sb_;
  jboolean aes_;
  jboolean finished_;
}

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                             withByteArray:(IOSByteArray *)key
                                   withInt:(jint)off
                                   withInt:(jint)len
                                   withInt:(jint)revision;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                             withByteArray:(IOSByteArray *)key
                                   withInt:(jint)revision;

- (void)close;

- (void)flush;

- (void)writeWithByteArray:(IOSByteArray *)b;

- (void)writeWithInt:(jint)b;

- (void)writeWithByteArray:(IOSByteArray *)b
                   withInt:(jint)off
                   withInt:(jint)len;

- (void)finish;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfOutputStreamEncryption *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfOutputStreamEncryption_init() {}

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfOutputStreamEncryption, out_, JavaIoOutputStream *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfOutputStreamEncryption, sb_, IOSByteArray *)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfOutputStreamEncryption, AES_128, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfOutputStreamEncryption, AES_256, jint)

#endif // _ComItextpdfTextPdfOutputStreamEncryption_H_
