//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PageResources.java
//

#ifndef _ComItextpdfTextPdfPageResources_H_
#define _ComItextpdfTextPdfPageResources_H_

#include "J2ObjC_header.h"

@class ComItextpdfTextPdfPdfDictionary;
@class ComItextpdfTextPdfPdfIndirectReference;
@class ComItextpdfTextPdfPdfName;
@class ComItextpdfTextPdfPdfObject;
@class IOSIntArray;
@class JavaUtilHashMap;
@class JavaUtilHashSet;

@interface ComItextpdfTextPdfPageResources : NSObject {
 @public
  ComItextpdfTextPdfPdfDictionary *fontDictionary_;
  ComItextpdfTextPdfPdfDictionary *xObjectDictionary_;
  ComItextpdfTextPdfPdfDictionary *colorDictionary_;
  ComItextpdfTextPdfPdfDictionary *patternDictionary_;
  ComItextpdfTextPdfPdfDictionary *shadingDictionary_;
  ComItextpdfTextPdfPdfDictionary *extGStateDictionary_;
  ComItextpdfTextPdfPdfDictionary *propertyDictionary_;
  JavaUtilHashSet *forbiddenNames_;
  ComItextpdfTextPdfPdfDictionary *originalResources_;
  IOSIntArray *namePtr_;
  JavaUtilHashMap *usedNames_;
}

#pragma mark Package-Private

- (instancetype)init;

- (ComItextpdfTextPdfPdfName *)addColorWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                          withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)reference;

- (void)addDefaultColorWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)dic;

- (void)addDefaultColorWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                     withComItextpdfTextPdfPdfObject:(ComItextpdfTextPdfPdfObject *)obj;

- (void)addDefaultColorDiffWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)dic;

- (ComItextpdfTextPdfPdfName *)addExtGStateWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                              withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)reference;

- (ComItextpdfTextPdfPdfName *)addFontWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                         withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)reference;

- (ComItextpdfTextPdfPdfName *)addPatternWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                            withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)reference;

- (ComItextpdfTextPdfPdfName *)addPropertyWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                             withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)reference;

- (ComItextpdfTextPdfPdfName *)addShadingWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                            withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)reference;

- (ComItextpdfTextPdfPdfName *)addXObjectWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                            withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)reference;

- (ComItextpdfTextPdfPdfDictionary *)getResources;

- (jboolean)hasResources;

- (void)setOriginalResourcesWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)resources
                                                   withIntArray:(IOSIntArray *)newNamePtr;

- (ComItextpdfTextPdfPdfName *)translateNameWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfPageResources)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, fontDictionary_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, xObjectDictionary_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, colorDictionary_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, patternDictionary_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, shadingDictionary_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, extGStateDictionary_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, propertyDictionary_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, forbiddenNames_, JavaUtilHashSet *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, originalResources_, ComItextpdfTextPdfPdfDictionary *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, namePtr_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPageResources, usedNames_, JavaUtilHashMap *)

FOUNDATION_EXPORT void ComItextpdfTextPdfPageResources_init(ComItextpdfTextPdfPageResources *self);

FOUNDATION_EXPORT ComItextpdfTextPdfPageResources *new_ComItextpdfTextPdfPageResources_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfPageResources)

#endif // _ComItextpdfTextPdfPageResources_H_
