//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfConcatenate.java
//

#ifndef _ComItextpdfTextPdfPdfConcatenate_H_
#define _ComItextpdfTextPdfPdfConcatenate_H_

#include "J2ObjC_header.h"

@class ComItextpdfTextDocument;
@class ComItextpdfTextPdfPdfCopy;
@class ComItextpdfTextPdfPdfReader;
@class JavaIoOutputStream;

@interface ComItextpdfTextPdfPdfConcatenate : NSObject {
 @public
  ComItextpdfTextDocument *document_;
  ComItextpdfTextPdfPdfCopy *copy__;
}

#pragma mark Public

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os;

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os
                               withBoolean:(jboolean)smart;

- (jint)addPagesWithComItextpdfTextPdfPdfReader:(ComItextpdfTextPdfPdfReader *)reader;

- (void)close;

- (ComItextpdfTextPdfPdfCopy *)getWriter;

- (void)open;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfPdfConcatenate)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPdfConcatenate, document_, ComItextpdfTextDocument *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPdfConcatenate, copy__, ComItextpdfTextPdfPdfCopy *)

FOUNDATION_EXPORT void ComItextpdfTextPdfPdfConcatenate_initWithJavaIoOutputStream_(ComItextpdfTextPdfPdfConcatenate *self, JavaIoOutputStream *os);

FOUNDATION_EXPORT ComItextpdfTextPdfPdfConcatenate *new_ComItextpdfTextPdfPdfConcatenate_initWithJavaIoOutputStream_(JavaIoOutputStream *os) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextPdfPdfConcatenate_initWithJavaIoOutputStream_withBoolean_(ComItextpdfTextPdfPdfConcatenate *self, JavaIoOutputStream *os, jboolean smart);

FOUNDATION_EXPORT ComItextpdfTextPdfPdfConcatenate *new_ComItextpdfTextPdfPdfConcatenate_initWithJavaIoOutputStream_withBoolean_(JavaIoOutputStream *os, jboolean smart) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfPdfConcatenate)

#endif // _ComItextpdfTextPdfPdfConcatenate_H_
