//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfFileSpecification.java
//

#ifndef _ComItextpdfTextPdfPdfFileSpecification_H_
#define _ComItextpdfTextPdfPdfFileSpecification_H_

@class ComItextpdfTextPdfCollectionPdfCollectionItem;
@class ComItextpdfTextPdfPdfIndirectReference;
@class ComItextpdfTextPdfPdfWriter;
@class IOSByteArray;
@class JavaIoOutputStream;

#import "JreEmulation.h"
#include "com/itextpdf/text/pdf/PdfDictionary.h"

@interface ComItextpdfTextPdfPdfFileSpecification : ComItextpdfTextPdfPdfDictionary {
 @public
  ComItextpdfTextPdfPdfWriter *writer_;
  ComItextpdfTextPdfPdfIndirectReference *ref_;
}

- (instancetype)init;

+ (ComItextpdfTextPdfPdfFileSpecification *)urlWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                  withNSString:(NSString *)url;

+ (ComItextpdfTextPdfPdfFileSpecification *)fileEmbeddedWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                           withNSString:(NSString *)filePath
                                                                           withNSString:(NSString *)fileDisplay
                                                                          withByteArray:(IOSByteArray *)fileStore;

+ (ComItextpdfTextPdfPdfFileSpecification *)fileEmbeddedWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                           withNSString:(NSString *)filePath
                                                                           withNSString:(NSString *)fileDisplay
                                                                          withByteArray:(IOSByteArray *)fileStore
                                                                                withInt:(jint)compressionLevel;

+ (ComItextpdfTextPdfPdfFileSpecification *)fileEmbeddedWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                           withNSString:(NSString *)filePath
                                                                           withNSString:(NSString *)fileDisplay
                                                                          withByteArray:(IOSByteArray *)fileStore
                                                                            withBoolean:(jboolean)compress;

+ (ComItextpdfTextPdfPdfFileSpecification *)fileEmbeddedWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                           withNSString:(NSString *)filePath
                                                                           withNSString:(NSString *)fileDisplay
                                                                          withByteArray:(IOSByteArray *)fileStore
                                                                            withBoolean:(jboolean)compress
                                                                           withNSString:(NSString *)mimeType
                                                    withComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)fileParameter;

+ (ComItextpdfTextPdfPdfFileSpecification *)fileEmbeddedWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                           withNSString:(NSString *)filePath
                                                                           withNSString:(NSString *)fileDisplay
                                                                          withByteArray:(IOSByteArray *)fileStore
                                                                           withNSString:(NSString *)mimeType
                                                    withComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)fileParameter
                                                                                withInt:(jint)compressionLevel;

+ (ComItextpdfTextPdfPdfFileSpecification *)fileExternWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                         withNSString:(NSString *)filePath;

- (ComItextpdfTextPdfPdfIndirectReference *)getReference;

- (void)setMultiByteFileNameWithByteArray:(IOSByteArray *)fileName;

- (void)setUnicodeFileNameWithNSString:(NSString *)filename
                           withBoolean:(jboolean)unicode;

- (void)setVolatileWithBoolean:(jboolean)volatile_file;

- (void)addDescriptionWithNSString:(NSString *)description_
                       withBoolean:(jboolean)unicode;

- (void)addCollectionItemWithComItextpdfTextPdfCollectionPdfCollectionItem:(ComItextpdfTextPdfCollectionPdfCollectionItem *)ci;

- (void)toPdfWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                      withJavaIoOutputStream:(JavaIoOutputStream *)os;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfPdfFileSpecification *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfPdfFileSpecification_init() {}

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPdfFileSpecification, writer_, ComItextpdfTextPdfPdfWriter *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPdfFileSpecification, ref_, ComItextpdfTextPdfPdfIndirectReference *)

#endif // _ComItextpdfTextPdfPdfFileSpecification_H_
