//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfFormField.java
//

#ifndef _ComItextpdfTextPdfPdfFormField_H_
#define _ComItextpdfTextPdfPdfFormField_H_

@class ComItextpdfTextPdfPdfAction;
@class ComItextpdfTextPdfPdfArray;
@class ComItextpdfTextPdfPdfDictionary;
@class ComItextpdfTextPdfPdfName;
@class ComItextpdfTextPdfPdfSignature;
@class ComItextpdfTextPdfPdfStamperImp;
@class ComItextpdfTextPdfPdfWriter;
@class ComItextpdfTextRectangle;
@class IOSObjectArray;
@class JavaUtilArrayList;

#import "JreEmulation.h"
#include "com/itextpdf/text/pdf/PdfAnnotation.h"

#define ComItextpdfTextPdfPdfFormField_FF_COMB 16777216
#define ComItextpdfTextPdfPdfFormField_FF_COMBO 131072
#define ComItextpdfTextPdfPdfFormField_FF_DONOTSCROLL 8388608
#define ComItextpdfTextPdfPdfFormField_FF_DONOTSPELLCHECK 4194304
#define ComItextpdfTextPdfPdfFormField_FF_EDIT 262144
#define ComItextpdfTextPdfPdfFormField_FF_FILESELECT 1048576
#define ComItextpdfTextPdfPdfFormField_FF_MULTILINE 4096
#define ComItextpdfTextPdfPdfFormField_FF_MULTISELECT 2097152
#define ComItextpdfTextPdfPdfFormField_FF_NO_EXPORT 4
#define ComItextpdfTextPdfPdfFormField_FF_NO_TOGGLE_TO_OFF 16384
#define ComItextpdfTextPdfPdfFormField_FF_PASSWORD 8192
#define ComItextpdfTextPdfPdfFormField_FF_PUSHBUTTON 65536
#define ComItextpdfTextPdfPdfFormField_FF_RADIO 32768
#define ComItextpdfTextPdfPdfFormField_FF_RADIOSINUNISON 33554432
#define ComItextpdfTextPdfPdfFormField_FF_READ_ONLY 1
#define ComItextpdfTextPdfPdfFormField_FF_REQUIRED 2
#define ComItextpdfTextPdfPdfFormField_FF_RICHTEXT 33554432
#define ComItextpdfTextPdfPdfFormField_MK_CAPTION_ABOVE 3
#define ComItextpdfTextPdfPdfFormField_MK_CAPTION_BELOW 2
#define ComItextpdfTextPdfPdfFormField_MK_CAPTION_LEFT 5
#define ComItextpdfTextPdfPdfFormField_MK_CAPTION_OVERLAID 6
#define ComItextpdfTextPdfPdfFormField_MK_CAPTION_RIGHT 4
#define ComItextpdfTextPdfPdfFormField_MK_NO_CAPTION 1
#define ComItextpdfTextPdfPdfFormField_MK_NO_ICON 0
#define ComItextpdfTextPdfPdfFormField_MULTILINE YES
#define ComItextpdfTextPdfPdfFormField_PASSWORD YES
#define ComItextpdfTextPdfPdfFormField_PLAINTEXT NO
#define ComItextpdfTextPdfPdfFormField_Q_CENTER 1
#define ComItextpdfTextPdfPdfFormField_Q_LEFT 0
#define ComItextpdfTextPdfPdfFormField_Q_RIGHT 2
#define ComItextpdfTextPdfPdfFormField_SINGLELINE NO

@interface ComItextpdfTextPdfPdfFormField : ComItextpdfTextPdfPdfAnnotation {
 @public
  ComItextpdfTextPdfPdfFormField *parent_;
  JavaUtilArrayList *kids_;
}

- (instancetype)initWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                          withFloat:(jfloat)llx
                                          withFloat:(jfloat)lly
                                          withFloat:(jfloat)urx
                                          withFloat:(jfloat)ury
                    withComItextpdfTextPdfPdfAction:(ComItextpdfTextPdfPdfAction *)action;

- (instancetype)initWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

- (void)setWidgetWithComItextpdfTextRectangle:(ComItextpdfTextRectangle *)rect
                withComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)highlight;

+ (ComItextpdfTextPdfPdfFormField *)createEmptyWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

- (void)setButtonWithInt:(jint)flags;

+ (ComItextpdfTextPdfPdfFormField *)createButtonWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                        withInt:(jint)flags;

+ (ComItextpdfTextPdfPdfFormField *)createPushButtonWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

+ (ComItextpdfTextPdfPdfFormField *)createCheckBoxWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

+ (ComItextpdfTextPdfPdfFormField *)createRadioButtonWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                         withBoolean:(jboolean)noToggleToOff;

+ (ComItextpdfTextPdfPdfFormField *)createTextFieldWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                       withBoolean:(jboolean)multiline
                                                                       withBoolean:(jboolean)password
                                                                           withInt:(jint)maxLen;

+ (ComItextpdfTextPdfPdfFormField *)createChoiceWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                        withInt:(jint)flags
                                                 withComItextpdfTextPdfPdfArray:(ComItextpdfTextPdfPdfArray *)options
                                                                        withInt:(jint)topIndex;

+ (ComItextpdfTextPdfPdfFormField *)createListWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                            withNSStringArray:(IOSObjectArray *)options
                                                                      withInt:(jint)topIndex;

+ (ComItextpdfTextPdfPdfFormField *)createListWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                           withNSStringArray2:(IOSObjectArray *)options
                                                                      withInt:(jint)topIndex;

+ (ComItextpdfTextPdfPdfFormField *)createComboWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                   withBoolean:(jboolean)edit
                                                             withNSStringArray:(IOSObjectArray *)options
                                                                       withInt:(jint)topIndex;

+ (ComItextpdfTextPdfPdfFormField *)createComboWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                                                                   withBoolean:(jboolean)edit
                                                            withNSStringArray2:(IOSObjectArray *)options
                                                                       withInt:(jint)topIndex;

+ (ComItextpdfTextPdfPdfArray *)processOptionsWithNSStringArray:(IOSObjectArray *)options;

+ (ComItextpdfTextPdfPdfArray *)processOptionsWithNSStringArray2:(IOSObjectArray *)options;

+ (ComItextpdfTextPdfPdfFormField *)createSignatureWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

- (ComItextpdfTextPdfPdfFormField *)getParent;

- (void)addKidWithComItextpdfTextPdfPdfFormField:(ComItextpdfTextPdfPdfFormField *)field;

- (JavaUtilArrayList *)getKids;

- (jint)setFieldFlagsWithInt:(jint)flags;

- (void)setValueAsStringWithNSString:(NSString *)s;

- (void)setValueAsNameWithNSString:(NSString *)s;

- (void)setValueWithComItextpdfTextPdfPdfSignature:(ComItextpdfTextPdfPdfSignature *)sig;

- (void)setRichValueWithNSString:(NSString *)rv;

- (void)setDefaultValueAsStringWithNSString:(NSString *)s;

- (void)setDefaultValueAsNameWithNSString:(NSString *)s;

- (void)setFieldNameWithNSString:(NSString *)s;

- (void)setUserNameWithNSString:(NSString *)s;

- (void)setMappingNameWithNSString:(NSString *)s;

- (void)setQuaddingWithInt:(jint)v;

+ (void)mergeResourcesWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)result
                      withComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)source
                      withComItextpdfTextPdfPdfStamperImp:(ComItextpdfTextPdfPdfStamperImp *)writer;

+ (void)mergeResourcesWithComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)result
                      withComItextpdfTextPdfPdfDictionary:(ComItextpdfTextPdfPdfDictionary *)source;

- (void)setUsed;

+ (ComItextpdfTextPdfPdfAnnotation *)shallowDuplicateWithComItextpdfTextPdfPdfAnnotation:(ComItextpdfTextPdfPdfAnnotation *)annot;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfPdfFormField *)other;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextPdfPdfFormField_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextPdfPdfFormField)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPdfFormField, parent_, ComItextpdfTextPdfPdfFormField *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPdfFormField, kids_, JavaUtilArrayList *)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_READ_ONLY, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_REQUIRED, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_NO_EXPORT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_NO_TOGGLE_TO_OFF, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_RADIO, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_PUSHBUTTON, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_MULTILINE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_PASSWORD, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_COMBO, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_EDIT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_FILESELECT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_MULTISELECT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_DONOTSPELLCHECK, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_DONOTSCROLL, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_COMB, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_RADIOSINUNISON, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, FF_RICHTEXT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, Q_LEFT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, Q_CENTER, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, Q_RIGHT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MK_NO_ICON, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MK_NO_CAPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MK_CAPTION_BELOW, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MK_CAPTION_ABOVE, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MK_CAPTION_RIGHT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MK_CAPTION_LEFT, jint)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MK_CAPTION_OVERLAID, jint)

FOUNDATION_EXPORT ComItextpdfTextPdfPdfName *ComItextpdfTextPdfPdfFormField_IF_SCALE_ALWAYS_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, IF_SCALE_ALWAYS_, ComItextpdfTextPdfPdfName *)

FOUNDATION_EXPORT ComItextpdfTextPdfPdfName *ComItextpdfTextPdfPdfFormField_IF_SCALE_BIGGER_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, IF_SCALE_BIGGER_, ComItextpdfTextPdfPdfName *)

FOUNDATION_EXPORT ComItextpdfTextPdfPdfName *ComItextpdfTextPdfPdfFormField_IF_SCALE_SMALLER_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, IF_SCALE_SMALLER_, ComItextpdfTextPdfPdfName *)

FOUNDATION_EXPORT ComItextpdfTextPdfPdfName *ComItextpdfTextPdfPdfFormField_IF_SCALE_NEVER_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, IF_SCALE_NEVER_, ComItextpdfTextPdfPdfName *)

FOUNDATION_EXPORT ComItextpdfTextPdfPdfName *ComItextpdfTextPdfPdfFormField_IF_SCALE_ANAMORPHIC_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, IF_SCALE_ANAMORPHIC_, ComItextpdfTextPdfPdfName *)

FOUNDATION_EXPORT ComItextpdfTextPdfPdfName *ComItextpdfTextPdfPdfFormField_IF_SCALE_PROPORTIONAL_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, IF_SCALE_PROPORTIONAL_, ComItextpdfTextPdfPdfName *)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, MULTILINE, jboolean)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, SINGLELINE, jboolean)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, PLAINTEXT, jboolean)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, PASSWORD, jboolean)

FOUNDATION_EXPORT IOSObjectArray *ComItextpdfTextPdfPdfFormField_mergeTarget_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfFormField, mergeTarget_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(ComItextpdfTextPdfPdfFormField, mergeTarget_, IOSObjectArray *)

#endif // _ComItextpdfTextPdfPdfFormField_H_
