//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfNull.java
//

#ifndef _ComItextpdfTextPdfPdfNull_H_
#define _ComItextpdfTextPdfPdfNull_H_

#import "JreEmulation.h"
#include "com/itextpdf/text/pdf/PdfObject.h"

@interface ComItextpdfTextPdfPdfNull : ComItextpdfTextPdfPdfObject {
}

- (instancetype)init;

- (NSString *)description;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextPdfPdfNull_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextPdfPdfNull)

FOUNDATION_EXPORT ComItextpdfTextPdfPdfNull *ComItextpdfTextPdfPdfNull_PDFNULL_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfNull, PDFNULL_, ComItextpdfTextPdfPdfNull *)

FOUNDATION_EXPORT NSString *ComItextpdfTextPdfPdfNull_CONTENT_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfPdfNull, CONTENT_, NSString *)

#endif // _ComItextpdfTextPdfPdfNull_H_
