//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfPTableEventSplit.java
//

#ifndef _ComItextpdfTextPdfPdfPTableEventSplit_H_
#define _ComItextpdfTextPdfPdfPTableEventSplit_H_

@class ComItextpdfTextPdfPdfPTable;

#import "JreEmulation.h"
#include "com/itextpdf/text/pdf/PdfPTableEvent.h"

@protocol ComItextpdfTextPdfPdfPTableEventSplit < ComItextpdfTextPdfPdfPTableEvent, NSObject, JavaObject >
- (void)splitTableWithComItextpdfTextPdfPdfPTable:(ComItextpdfTextPdfPdfPTable *)table;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfPdfPTableEventSplit_init() {}

#endif // _ComItextpdfTextPdfPdfPTableEventSplit_H_
