//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfPCellEvent.java
//

#ifndef _ComItextpdfTextPdfPdfPCellEvent_H_
#define _ComItextpdfTextPdfPdfPCellEvent_H_

#include "J2ObjC_header.h"

@class ComItextpdfTextPdfPdfPCell;
@class ComItextpdfTextRectangle;
@class IOSObjectArray;

@protocol ComItextpdfTextPdfPdfPCellEvent < NSObject, JavaObject >

- (void)cellLayoutWithComItextpdfTextPdfPdfPCell:(ComItextpdfTextPdfPdfPCell *)cell
                    withComItextpdfTextRectangle:(ComItextpdfTextRectangle *)position
       withComItextpdfTextPdfPdfContentByteArray:(IOSObjectArray *)canvases;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfPdfPCellEvent)

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfPdfPCellEvent)

#endif // _ComItextpdfTextPdfPdfPCellEvent_H_
