//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfSigLockDictionary.java
//

#line 1 "/Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfSigLockDictionary.java"

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/itextpdf/text/pdf/PdfArray.h"
#include "com/itextpdf/text/pdf/PdfName.h"
#include "com/itextpdf/text/pdf/PdfNumber.h"
#include "com/itextpdf/text/pdf/PdfSigLockDictionary.h"
#include "com/itextpdf/text/pdf/PdfString.h"
#include "java/lang/IllegalArgumentException.h"


#line 50
@implementation ComItextpdfTextPdfPdfSigLockDictionary


#line 93
- (instancetype)initComItextpdfTextPdfPdfSigLockDictionary {
  if (self =
#line 94
  [super initWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_SIGFIELDLOCK_()]) {
    
#line 95
    [self putWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_ACTION_() withComItextpdfTextPdfPdfObject:[((ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *) nil_chk(ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_get_ALL())) getValue]];
  }
  return self;
}

- (instancetype)init {
  return [self initComItextpdfTextPdfPdfSigLockDictionary];
}


#line 102
- (instancetype)initWithComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum:(ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *)p {
  if (self =
#line 103
  [self initComItextpdfTextPdfPdfSigLockDictionary]) {
    
#line 104
    [self putWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_P_() withComItextpdfTextPdfPdfObject:[((ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *) nil_chk(p)) getValue]];
  }
  return self;
}


#line 110
- (instancetype)initWithComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum:(ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *)action
                                                            withNSStringArray:(IOSObjectArray *)fields {
  return
#line 111
  [self initComItextpdfTextPdfPdfSigLockDictionaryWithComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum:action withComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum:nil withNSStringArray:fields];
}

- (instancetype)initComItextpdfTextPdfPdfSigLockDictionaryWithComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum:(ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *)action
                                                     withComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum:(ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *)p
                                                                                                  withNSStringArray:(IOSObjectArray *)fields {
  if (self =
#line 118
  [super initWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_SIGFIELDLOCK_()]) {
    
#line 119
    [self putWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_ACTION_() withComItextpdfTextPdfPdfObject:[((ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *) nil_chk(action)) getValue]];
    
#line 120
    if (p != nil)
#line 121
    [self putWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_P_() withComItextpdfTextPdfPdfObject:[p getValue]];
    
#line 122
    ComItextpdfTextPdfPdfArray *fieldsArray = [[ComItextpdfTextPdfPdfArray alloc] init];
    {
      IOSObjectArray *a__ =
#line 123
      fields;
      NSString * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
      NSString * const *e__ = b__ + a__->size_;
      while (b__ < e__) {
        NSString *field = *b__++;
        
#line 124
        [fieldsArray addWithComItextpdfTextPdfPdfObject:[[ComItextpdfTextPdfPdfString alloc] initWithNSString:field]];
      }
    }
    
#line 126
    [self putWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_FIELDS_() withComItextpdfTextPdfPdfObject:fieldsArray];
  }
  return self;
}

- (instancetype)initWithComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum:(ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *)action
               withComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum:(ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *)p
                                                            withNSStringArray:(IOSObjectArray *)fields {
  return [self initComItextpdfTextPdfPdfSigLockDictionaryWithComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum:
#line 117
action withComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum:p withNSStringArray:fields];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "PdfSigLockDictionary", NULL, 0x1, NULL },
    { "initWithComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum:", "PdfSigLockDictionary", NULL, 0x1, NULL },
    { "initWithComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum:withNSStringArray:", "PdfSigLockDictionary", NULL, 0x81, NULL },
    { "initWithComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum:withComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum:withNSStringArray:", "PdfSigLockDictionary", NULL, 0x81, NULL },
  };
  static const J2ObjcClassInfo _ComItextpdfTextPdfPdfSigLockDictionary = { "PdfSigLockDictionary", "com.itextpdf.text.pdf", NULL, 0x1, 4, methods, 0, NULL, 0, NULL};
  return &_ComItextpdfTextPdfPdfSigLockDictionary;
}

@end

#line 59

BOOL ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_initialized = NO;

ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_values_[3];

@implementation ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum


#line 64
- (instancetype)initWithComItextpdfTextPdfPdfName:(ComItextpdfTextPdfPdfName *)name
                                     withNSString:(NSString *)__name
                                          withInt:(jint)__ordinal {
  if (self = [super initWithNSString:__name withInt:__ordinal]) {
    self->name_LockAction_ = name;
  }
  return self;
}


#line 68
- (ComItextpdfTextPdfPdfName *)getValue {
  
#line 69
  return name_LockAction_;
}

FOUNDATION_EXPORT IOSObjectArray *ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_values() {
  return [IOSObjectArray arrayWithObjects:ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_values_ count:3 type:[IOSClass classWithClass:[ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum class]]];
}
+ (IOSObjectArray *)values {
  return ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_values();
}

+ (ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *)valueOfWithNSString:(NSString *)name {
  return ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_valueOfWithNSString_(name);
}

ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_valueOfWithNSString_(NSString *name) {
  for (int i = 0; i < 3; i++) {
    ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum *e = ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum class]) {
    ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_ALL = [[ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum alloc] initWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_ALL_() withNSString:@"ALL" withInt:0];
    ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_INCLUDE = [[ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum alloc] initWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_INCLUDE_() withNSString:@"INCLUDE" withInt:1];
    ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_EXCLUDE = [[ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum alloc] initWithComItextpdfTextPdfPdfName:ComItextpdfTextPdfPdfName_get_EXCLUDE_() withNSString:@"EXCLUDE" withInt:2];
    ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_initialized = YES;
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComItextpdfTextPdfPdfName:withNSString:withInt:", "LockAction", NULL, 0x2, NULL },
    { "getValue", NULL, "Lcom.itextpdf.text.pdf.PdfName;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ALL", "ALL", 0x4019, "Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockAction;", &ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_ALL,  },
    { "INCLUDE", "INCLUDE", 0x4019, "Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockAction;", &ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_INCLUDE,  },
    { "EXCLUDE", "EXCLUDE", 0x4019, "Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockAction;", &ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum_EXCLUDE,  },
    { "name_LockAction_", "name", 0x2, "Lcom.itextpdf.text.pdf.PdfName;", NULL,  },
  };
  static const char *superclass_type_args[] = {"Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockAction;"};
  static const J2ObjcClassInfo _ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum = { "LockAction", "com.itextpdf.text.pdf", "PdfSigLockDictionary", 0x4019, 2, methods, 4, fields, 1, superclass_type_args};
  return &_ComItextpdfTextPdfPdfSigLockDictionary_LockActionEnum;
}

@end

#line 76

BOOL ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_initialized = NO;

ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_values_[3];

@implementation ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum


#line 81
- (instancetype)initWithInt:(jint)p
               withNSString:(NSString *)__name
                    withInt:(jint)__ordinal {
  if (self = [super initWithNSString:__name withInt:__ordinal]) {
    number_ = [[ComItextpdfTextPdfPdfNumber alloc] initWithInt:p];
  }
  return self;
}


#line 85
- (ComItextpdfTextPdfPdfNumber *)getValue {
  
#line 86
  return number_;
}

FOUNDATION_EXPORT IOSObjectArray *ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_values() {
  return [IOSObjectArray arrayWithObjects:ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_values_ count:3 type:[IOSClass classWithClass:[ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum class]]];
}
+ (IOSObjectArray *)values {
  return ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_values();
}

+ (ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *)valueOfWithNSString:(NSString *)name {
  return ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_valueOfWithNSString_(name);
}

ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_valueOfWithNSString_(NSString *name) {
  for (int i = 0; i < 3; i++) {
    ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum *e = ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum class]) {
    ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_NO_CHANGES_ALLOWED = [[ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum alloc] initWithInt:
#line 77
    1 withNSString:@"NO_CHANGES_ALLOWED" withInt:0];
    ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_FORM_FILLING = [[ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum alloc] initWithInt:
#line 77
    2 withNSString:@"FORM_FILLING" withInt:1];
    ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_FORM_FILLING_AND_ANNOTATION = [[ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum alloc] initWithInt:
#line 77
    3 withNSString:@"FORM_FILLING_AND_ANNOTATION" withInt:2];
    ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_initialized = YES;
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:withNSString:withInt:", "LockPermissions", NULL, 0x2, NULL },
    { "getValue", NULL, "Lcom.itextpdf.text.pdf.PdfNumber;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NO_CHANGES_ALLOWED", "NO_CHANGES_ALLOWED", 0x4019, "Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockPermissions;", &ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_NO_CHANGES_ALLOWED,  },
    { "FORM_FILLING", "FORM_FILLING", 0x4019, "Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockPermissions;", &ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_FORM_FILLING,  },
    { "FORM_FILLING_AND_ANNOTATION", "FORM_FILLING_AND_ANNOTATION", 0x4019, "Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockPermissions;", &ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum_FORM_FILLING_AND_ANNOTATION,  },
    { "number_", NULL, 0x2, "Lcom.itextpdf.text.pdf.PdfNumber;", NULL,  },
  };
  static const char *superclass_type_args[] = {"Lcom.itextpdf.text.pdf.PdfSigLockDictionary$LockPermissions;"};
  static const J2ObjcClassInfo _ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum = { "LockPermissions", "com.itextpdf.text.pdf", "PdfSigLockDictionary", 0x4019, 2, methods, 4, fields, 1, superclass_type_args};
  return &_ComItextpdfTextPdfPdfSigLockDictionary_LockPermissionsEnum;
}

@end
