//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PdfTextArray.java
//

#ifndef _ComItextpdfTextPdfPdfTextArray_H_
#define _ComItextpdfTextPdfPdfTextArray_H_

#include "J2ObjC_header.h"

@class ComItextpdfTextPdfPdfNumber;
@class JavaUtilArrayList;

@interface ComItextpdfTextPdfPdfTextArray : NSObject {
 @public
  JavaUtilArrayList *arrayList_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)str;

- (void)addWithFloat:(jfloat)number;

- (void)addWithComItextpdfTextPdfPdfNumber:(ComItextpdfTextPdfPdfNumber *)number;

- (void)addWithNSString:(NSString *)str;

#pragma mark Package-Private

- (JavaUtilArrayList *)getArrayList;

@end

J2OBJC_EMPTY_STATIC_INIT(ComItextpdfTextPdfPdfTextArray)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPdfTextArray, arrayList_, JavaUtilArrayList *)

FOUNDATION_EXPORT void ComItextpdfTextPdfPdfTextArray_initWithNSString_(ComItextpdfTextPdfPdfTextArray *self, NSString *str);

FOUNDATION_EXPORT ComItextpdfTextPdfPdfTextArray *new_ComItextpdfTextPdfPdfTextArray_initWithNSString_(NSString *str) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComItextpdfTextPdfPdfTextArray_init(ComItextpdfTextPdfPdfTextArray *self);

FOUNDATION_EXPORT ComItextpdfTextPdfPdfTextArray *new_ComItextpdfTextPdfPdfTextArray_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComItextpdfTextPdfPdfTextArray)

#endif // _ComItextpdfTextPdfPdfTextArray_H_
