//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/PRIndirectReference.java
//

#ifndef _ComItextpdfTextPdfPRIndirectReference_H_
#define _ComItextpdfTextPdfPRIndirectReference_H_

@class ComItextpdfTextPdfPdfReader;
@class ComItextpdfTextPdfPdfWriter;
@class JavaIoOutputStream;

#import "JreEmulation.h"
#include "com/itextpdf/text/pdf/PdfIndirectReference.h"

@interface ComItextpdfTextPdfPRIndirectReference : ComItextpdfTextPdfPdfIndirectReference {
 @public
  ComItextpdfTextPdfPdfReader *reader_;
}

- (instancetype)initWithComItextpdfTextPdfPdfReader:(ComItextpdfTextPdfPdfReader *)reader
                                            withInt:(jint)number
                                            withInt:(jint)generation;

- (instancetype)initWithComItextpdfTextPdfPdfReader:(ComItextpdfTextPdfPdfReader *)reader
                                            withInt:(jint)number;

- (void)toPdfWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
                      withJavaIoOutputStream:(JavaIoOutputStream *)os;

- (ComItextpdfTextPdfPdfReader *)getReader;

- (void)setNumberWithInt:(jint)number
                 withInt:(jint)generation;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfPRIndirectReference *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfPRIndirectReference_init() {}

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfPRIndirectReference, reader_, ComItextpdfTextPdfPdfReader *)

#endif // _ComItextpdfTextPdfPRIndirectReference_H_
