//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/ShadingColor.java
//

#ifndef _ComItextpdfTextPdfShadingColor_H_
#define _ComItextpdfTextPdfShadingColor_H_

@class ComItextpdfTextPdfPdfShadingPattern;

#import "JreEmulation.h"
#include "com/itextpdf/text/pdf/ExtendedColor.h"

#define ComItextpdfTextPdfShadingColor_serialVersionUID 4817929454941328671LL

@interface ComItextpdfTextPdfShadingColor : ComItextpdfTextPdfExtendedColor {
 @public
  ComItextpdfTextPdfPdfShadingPattern *shadingPattern_;
}

- (instancetype)initWithComItextpdfTextPdfPdfShadingPattern:(ComItextpdfTextPdfPdfShadingPattern *)shadingPattern;

- (ComItextpdfTextPdfPdfShadingPattern *)getPdfShadingPattern;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfShadingColor *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfShadingColor_init() {}

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfShadingColor, shadingPattern_, ComItextpdfTextPdfPdfShadingPattern *)

J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfShadingColor, serialVersionUID, jlong)

#endif // _ComItextpdfTextPdfShadingColor_H_
