//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/SimpleNamedDestination.java
//

#ifndef _ComItextpdfTextPdfSimpleNamedDestination_H_
#define _ComItextpdfTextPdfSimpleNamedDestination_H_

@class ComItextpdfTextPdfPdfArray;
@class ComItextpdfTextPdfPdfDictionary;
@class ComItextpdfTextPdfPdfReader;
@class ComItextpdfTextPdfPdfWriter;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaIoReader;
@class JavaIoWriter;
@class JavaUtilHashMap;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "com/itextpdf/text/xml/simpleparser/SimpleXMLDocHandler.h"

@interface ComItextpdfTextPdfSimpleNamedDestination : NSObject < ComItextpdfTextXmlSimpleparserSimpleXMLDocHandler > {
 @public
  JavaUtilHashMap *xmlNames_;
  JavaUtilHashMap *xmlLast_;
}

- (instancetype)init;

+ (JavaUtilHashMap *)getNamedDestinationWithComItextpdfTextPdfPdfReader:(ComItextpdfTextPdfPdfReader *)reader
                                                            withBoolean:(jboolean)fromNames;

+ (void)exportToXMLWithJavaUtilHashMap:(JavaUtilHashMap *)names
                withJavaIoOutputStream:(JavaIoOutputStream *)outArg
                          withNSString:(NSString *)encoding
                           withBoolean:(jboolean)onlyASCII;

+ (void)exportToXMLWithJavaUtilHashMap:(JavaUtilHashMap *)names
                      withJavaIoWriter:(JavaIoWriter *)wrt
                          withNSString:(NSString *)encoding
                           withBoolean:(jboolean)onlyASCII;

+ (JavaUtilHashMap *)importFromXMLWithJavaIoInputStream:(JavaIoInputStream *)inArg;

+ (JavaUtilHashMap *)importFromXMLWithJavaIoReader:(JavaIoReader *)inArg;

+ (ComItextpdfTextPdfPdfArray *)createDestinationArrayWithNSString:(NSString *)value
                                   withComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

+ (ComItextpdfTextPdfPdfDictionary *)outputNamedDestinationAsNamesWithJavaUtilHashMap:(JavaUtilHashMap *)names
                                                      withComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

+ (ComItextpdfTextPdfPdfDictionary *)outputNamedDestinationAsStringsWithJavaUtilHashMap:(JavaUtilHashMap *)names
                                                        withComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer;

+ (NSString *)escapeBinaryStringWithNSString:(NSString *)s;

+ (NSString *)unEscapeBinaryStringWithNSString:(NSString *)s;

- (void)endDocument;

- (void)endElementWithNSString:(NSString *)tag;

- (void)startDocument;

- (void)startElementWithNSString:(NSString *)tag
                 withJavaUtilMap:(id<JavaUtilMap>)h;

- (void)textWithNSString:(NSString *)str;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfSimpleNamedDestination *)other;

@end

__attribute__((always_inline)) inline void ComItextpdfTextPdfSimpleNamedDestination_init() {}

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfSimpleNamedDestination, xmlNames_, JavaUtilHashMap *)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfSimpleNamedDestination, xmlLast_, JavaUtilHashMap *)

#endif // _ComItextpdfTextPdfSimpleNamedDestination_H_
