//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/SimarisCurves/com.itextpdf/src/com/itextpdf/text/pdf/TrueTypeFontUnicode.java
//

#ifndef _ComItextpdfTextPdfTrueTypeFontUnicode_H_
#define _ComItextpdfTextPdfTrueTypeFontUnicode_H_

@class ComItextpdfTextPdfFontsOtfLanguageEnum;
@class ComItextpdfTextPdfPdfDictionary;
@class ComItextpdfTextPdfPdfIndirectReference;
@class ComItextpdfTextPdfPdfStream;
@class ComItextpdfTextPdfPdfWriter;
@class IOSByteArray;
@class IOSIntArray;
@class IOSObjectArray;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "com/itextpdf/text/pdf/TrueTypeFont.h"
#include "java/util/Comparator.h"

@interface ComItextpdfTextPdfTrueTypeFontUnicode : ComItextpdfTextPdfTrueTypeFont < JavaUtilComparator > {
 @public
  id<JavaUtilMap> glyphSubstitutionMap_;
  ComItextpdfTextPdfFontsOtfLanguageEnum *supportedLanguage_;
}

- (instancetype)initWithNSString:(NSString *)ttFile
                    withNSString:(NSString *)enc
                     withBoolean:(jboolean)emb
                   withByteArray:(IOSByteArray *)ttfAfm
                     withBoolean:(jboolean)forceRead;

- (void)processWithByteArray:(IOSByteArray *)ttfAfm
                 withBoolean:(jboolean)preload;

- (jint)getWidthWithInt:(jint)char1;

- (jint)getWidthWithNSString:(NSString *)text;

- (ComItextpdfTextPdfPdfStream *)getToUnicodeWithNSObjectArray:(IOSObjectArray *)metrics;

+ (NSString *)toHex4WithInt:(jint)n;

+ (NSString *)toHexWithInt:(jint)n;

- (ComItextpdfTextPdfPdfDictionary *)getCIDFontType2WithComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)fontDescriptor
                                                                                  withNSString:(NSString *)subsetPrefix
                                                                             withNSObjectArray:(IOSObjectArray *)metrics;

- (ComItextpdfTextPdfPdfDictionary *)getFontBaseTypeWithComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)descendant
                                                                                  withNSString:(NSString *)subsetPrefix
                                                    withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)toUnicode;

- (jint)compareWithId:(IOSIntArray *)o1
               withId:(IOSIntArray *)o2;

- (void)writeFontWithComItextpdfTextPdfPdfWriter:(ComItextpdfTextPdfPdfWriter *)writer
      withComItextpdfTextPdfPdfIndirectReference:(ComItextpdfTextPdfPdfIndirectReference *)ref
                               withNSObjectArray:(IOSObjectArray *)params;

- (ComItextpdfTextPdfPdfStream *)getFullFontStream;

- (IOSByteArray *)convertToBytesWithNSString:(NSString *)text;

- (IOSByteArray *)convertToBytesWithInt:(jint)char1;

- (IOSIntArray *)getMetricsTTWithInt:(jint)c;

- (jboolean)charExistsWithInt:(jint)c;

- (jboolean)setCharAdvanceWithInt:(jint)c
                          withInt:(jint)advance;

- (IOSIntArray *)getCharBBoxWithInt:(jint)c;

- (id<JavaUtilMap>)getGlyphSubstitutionMap;

- (ComItextpdfTextPdfFontsOtfLanguageEnum *)getSupportedLanguage;

- (void)readGsubTable;

- (void)copyAllFieldsTo:(ComItextpdfTextPdfTrueTypeFontUnicode *)other;

@end

FOUNDATION_EXPORT BOOL ComItextpdfTextPdfTrueTypeFontUnicode_initialized;
J2OBJC_STATIC_INIT(ComItextpdfTextPdfTrueTypeFontUnicode)

J2OBJC_FIELD_SETTER(ComItextpdfTextPdfTrueTypeFontUnicode, glyphSubstitutionMap_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComItextpdfTextPdfTrueTypeFontUnicode, supportedLanguage_, ComItextpdfTextPdfFontsOtfLanguageEnum *)

FOUNDATION_EXPORT id<JavaUtilList> ComItextpdfTextPdfTrueTypeFontUnicode_SUPPORTED_LANGUAGES_FOR_OTF_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfTrueTypeFontUnicode, SUPPORTED_LANGUAGES_FOR_OTF_, id<JavaUtilList>)

FOUNDATION_EXPORT IOSByteArray *ComItextpdfTextPdfTrueTypeFontUnicode_rotbits_;
J2OBJC_STATIC_FIELD_GETTER(ComItextpdfTextPdfTrueTypeFontUnicode, rotbits_, IOSByteArray *)

#endif // _ComItextpdfTextPdfTrueTypeFontUnicode_H_
